silverstripe/silverstripe-cms

- javascript/CMSMain.EditForm.js
- javascript/lang/en.js
- javascript/lang/src/en.js
Missing translation entity on Update URL button.
> FIX. Missing translation entity

- code/controllers/AssetAdmin.php
I think this should fix the issue; there is no need for those buttons to be there anyway except for on Root.DetailsView?  Can someone confirm whether or not this change will cause any unforeseen issues?
> Issue #1150: Removed Save and Delete buttons from regular edit form.

- code/model/SiteTreeFileExtension.php
- code/model/SiteTreeFolderExtension.php
- code/model/SiteTreeLinkTracking.php
- code/model/VirtualPage.php
See https://github.com/silverstripe/silverstripe-framework/pull/3799
> Updating deprecated functions

- code/controllers/AssetAdmin.php
- code/controllers/CMSFileAddController.php
- code/controllers/CMSMain.php
- code/controllers/CMSPageAddController.php
- code/controllers/CMSPageHistoryController.php
- code/controllers/CMSPagesController.php
- code/controllers/ContentController.php
- code/controllers/ModelAsController.php
- code/search/ContentControllerSearchExtension.php
See https://github.com/silverstripe/silverstripe-cms/pull/1194#issuecomment-97573329
> UPDATE: change all instances of $this->request to use appropriate getter/setter

- code/controllers/AssetAdmin.php
This is a companion fix for https://github.com/silverstripe/silverstripe-framework/pull/4202
> FIX: Folder expansion icons

- code/batchactions/CMSBatchActions.php
- code/controllers/CMSMain.php
- code/controllers/CMSSiteTreeFilter.php
- code/model/SiteTree.php
- tests/model/FileLinkTrackingTest.php
- tests/model/SiteTreeTest.php
- tests/model/VirtualPageTest.php
> FIX: explicitly call get functions for site tree checks

- code/model/SiteTree.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/4258
> API Formalise new DataObject::canCreate argument

- code/model/SiteTree.php
- code/model/VirtualPage.php
To go with https://github.com/silverstripe/silverstripe-framework/pull/4286
> API Revert DataObject::validate to 3.1 method signature (protected)

- code/model/SiteTree.php
- code/model/VirtualPage.php
See https://github.com/silverstripe/silverstripe-framework/pull/4294
> API make DataObject::validate public

- code/controllers/ModelAsController.php
- code/controllers/RootURLController.php
- code/model/ErrorPage.php
- code/model/SiteTree.php
- code/model/SiteTreeFileExtension.php
cc @silverstripe/core-team @hafriedlander 
See https://github.com/silverstripe/silverstripe-framework/pull/4310
> Set deprecation level for all changes in 3.x to 4.0

- tests/behat/features/insert-a-link.feature
> BUG fix behat tests

- css/screen.css
- scss/_CMSMain.scss
- templates/Includes/CMSPagesController_ContentToolActions.ss
Needed for https://github.com/silverstripe/silverstripe-framework/pull/4353
> Update button styles

- .travis.yml
- javascript/CMSMain.AddForm.js
- tests/behat/features/insert-an-image.feature
Must be merged with https://github.com/silverstripe/silverstripe-framework/pull/4390
> API respect custom attributes on OptionsetField and CheckboxSetField

- javascript/lang/en.js
- javascript/lang/src/en.js
Also: https://github.com/silverstripe/silverstripe-framework/pull/4470
> Update archive warning to include children pages

- code/batchactions/CMSBatchActions.php
- code/controllers/CMSMain.php
- code/model/SiteTree.php
- tests/controller/CMSBatchActionsTest.php
- tests/controller/CMSBatchActionsTest.yml
- tests/model/SiteTreeTest.php
Alternative solution to https://github.com/silverstripe/silverstripe-cms/pull/1255
> API batch restore action (ALTERNATE SOLUTION)

- code/batchactions/CMSBatchActions.php
- code/controllers/CMSSiteTreeFilter.php
- code/model/SiteTreeFolderExtension.php
- code/model/SiteTreeLinkTracking.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/4476
Also merge https://github.com/silverstripe/silverstripe-framework/issues/4532
> Fix missing packages

- code/model/SiteTree.php
- tests/model/SiteTreeTest.php
> BUG block adding children from archived pages

- javascript/CMSMain.Tree.js
- lang/en.yml
- templates/Includes/CMSMain_ListView.ss
- templates/Includes/CMSMain_TreeView.ss
To be merged with https://github.com/silverstripe/silverstripe-framework/pull/4529
> Update the filtered tree styling

- .travis.yml
Companion to https://github.com/silverstripe/silverstripe-framework/pull/4535
> MINOR: Remove IRC notifications of travis builds.

- code/controllers/AssetAdmin.php
- css/screen.css
- scss/_CMSMain.scss
- templates/Includes/AssetAdmin_Content.ss
- templates/Includes/CMSMain_Content.ss
- templates/Includes/CMSPagesController_Content.ss
- templates/Includes/CMSPagesController_ContentToolActions.ss
Needed with - https://github.com/silverstripe/silverstripe-framework/pull/4536
> Update font icons to use new library

- code/controllers/AssetAdmin.php
- code/controllers/CMSMain.php
- code/controllers/ModelAsController.php
- code/controllers/RootURLController.php
- code/model/ErrorPage.php
Needs https://github.com/silverstripe/silverstripe-framework/pull/4500
> UPDATE: make all response code use getResponse() method

- code/controllers/AssetAdmin.php
- code/controllers/CMSMain.php
- code/controllers/CMSPageAddController.php
- code/controllers/CMSPageHistoryController.php
- code/controllers/CMSPageSettingsController.php
- code/controllers/CMSPagesController.php
- code/controllers/CMSSiteTreeFilter.php
- code/controllers/ContentController.php
- code/controllers/ErrorPageControllerExtension.php
- code/controllers/LeftAndMainPageIconsExtension.php
- code/controllers/ModelAsController.php
- code/controllers/NestedController.php
- code/controllers/OldPageRedirector.php
- code/controllers/RootURLController.php
- code/controllers/SilverStripeNavigator.php
reopen https://github.com/silverstripe/silverstripe-cms/pull/1284 pointing at master
> remove trailing spaces in the codebase

- .travis.yml
- composer.json
See mailinglist discussion at https://groups.google.com/forum/#!topic/silverstripe-dev/7mVvhNNeNps
> Increase minimum required PHP version to 5.5

- code/controllers/AssetAdmin.php
- css/screen.css
- javascript/AssetAdmin.js
- scss/_AssetAdmin.scss
- templates/Includes/AssetAdmin_Content.ss
- templates/Includes/CMSMain_Content.ss
- templates/Includes/CMSPagesController_Content.ss
- tests/behat/features/insert-an-image.feature
To be merged with - https://github.com/silverstripe/silverstripe-framework/pull/4701
CMS Behat tests won't pass until framework PR is merged.
> Update asset admin toolbar

- css/screen.css
- scss/_AssetAdmin.scss
For https://github.com/silverstripe/silverstripe-framework/pull/4744
> move allowed extensions into a sidebar

- code/model/SiteTree.php
Required for extended audit logging in CWP
> Extension hooks for "restore to stage" and "archive"

- code/reports/BrokenFilesReport.php
- code/reports/BrokenLinksReport.php
- code/reports/BrokenRedirectorPagesReport.php
- code/reports/BrokenVirtualPagesReport.php
- code/reports/EmptyPagesReport.php
- code/reports/RecentlyEditedReport.php
- tests/reports/CmsReportsTest.php
Merge with https://github.com/silverstripe-labs/silverstripe-reports/pull/12
Fixes https://github.com/silverstripe/silverstripe-framework/issues/4703
> Restore deprecated reports

- code/model/SiteTree.php
Reverts silverstripe/silverstripe-cms#1319
> Revert 7e2838c81c5a83bcaedd0ca782f7ee9afc909001

- code/model/ErrorPage.php
- tests/model/ErrorPageTest.php
CMS pull request for https://github.com/silverstripe/silverstripe-framework/pull/4796
> API Update ErrorPage to use FilesystemGeneratedAssetHandler

- code/controllers/ContentController.php
- code/model/SiteTree.php
CMS component for https://github.com/silverstripe/silverstripe-framework/pull/4831
> API Refactor versioned security into core module

- tests/controller/ContentControllerPermissionsTest.php
- tests/controller/ContentControllerTest.php
- tests/model/SiteTreePermissionsTest.php
Once https://github.com/silverstripe/silverstripe-framework/pull/4867 is merged, this change will fix breaking tests.
> BUG Fix merge regressions in versioned tests

- code/controllers/ContentController.php
Depends on https://github.com/silverstripe/silverstripe-framework/pull/4870.
> Use setFailover() in ContentController (closes silverstripe/silverstripe-framework#4821)

- code/model/SiteTree.php
CMS pr for https://github.com/silverstripe/silverstripe-framework/pull/4568
> API Use new formfields

- javascript/CMSMain.AddForm.js
Fixes https://github.com/silverstripe/silverstripe-framework/issues/4540
> BUG Fix incorrect "Add Page" button selector

- code/model/SiteTree.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/1932
Requires https://github.com/silverstripe/silverstripe-framework/pull/4962
> API Refactor out Page default classname hack

- templates/Includes/CMSPagesController_Content.ss
Fixes https://github.com/silverstripe/silverstripe-framework/issues/4945
> BUG Don't keep stale treeview data when refreshing Content area

- code/controllers/AssetAdmin.php
Required for https://github.com/silverstripe/silverstripe-framework/pull/4937
> Implement RFC-7 JavaScript module loader

- code/model/VirtualPage.php
- tests/model/VirtualPageTest.php
- tests/model/VirtualPageTest.yml
Replaces https://github.com/silverstripe/silverstripe-cms/pull/1373
Fixes #1318
> API VirtualPage permissions now can be set independently of the mirrored page

- code/controllers/CMSMain.php
This depends on https://github.com/silverstripe/silverstripe-framework/pull/5005
> Removing stage reading mode as it will be set in LeftAndMain

- templates/Includes/AssetAdmin_Content.ss
- templates/Includes/CMSMain_Content.ss
- templates/Includes/CMSPagesController_Content.ss
Merge with https://github.com/silverstripe/silverstripe-framework/pull/5009
> Add no-text class to search icon

- tests/behat/features/apply-formatting.feature
- tests/behat/features/create-a-page.feature
- tests/behat/features/edit-a-page.feature
- tests/behat/features/insert-a-link.feature
- tests/behat/features/insert-an-image.feature
- tests/behat/features/manage-page-permissions.feature
- tests/behat/features/preview-a-page.feature
- tests/behat/features/publish-a-page.feature
- tests/behat/features/search-for-a-page.feature
- tests/behat/features/view-reports.feature
Updated tests for https://github.com/silverstripe/silverstripe-framework/pull/5037
I've run these locally to confirm they work; Some changes to the core behat context were necessary.
> Upgrade TinyMCE to 4.x

- tests/behat/features/insert-a-link.feature
- tests/behat/features/insert-an-image.feature
- tests/behat/features/manage-files.feature
Requires https://github.com/silverstripe-labs/silverstripe-behat-extension/pull/111
Also corrects reference from "Delete" to "Archive" in asset admin, since assets are now versioned.
> BUG Fix behat tests for asset abstraction

- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/bootstrap/SilverStripe/Cms/Test/Behaviour/FixtureContext.php
- tests/behat/features/bootstrap/SilverStripe/Cms/Test/Behaviour/ThemeContext.php
Merge dependant on:
* https://github.com/silverstripe/silverstripe-framework/pull/4980
* https://github.com/silverstripe-labs/silverstripe-behat-extension/pull/104
* https://github.com/silverstripe/silverstripe-installer/pull/112
/cc @dhensby
> Remove Behat-related code dependant on PHPUnit 3.x

- code/controllers/CMSPageAddController.php
To go with https://github.com/silverstripe/silverstripe-translatable/pull/231
> Removed dependency for translatable module

- code/model/SiteTree.php
Typo fix (change "dedcide" to "decide")
> Fix decide typo in comment

- code/controllers/AssetAdmin.php
- code/controllers/CMSMain.php
- code/controllers/CMSPageAddController.php
- code/controllers/CMSPageHistoryController.php
- tests/controller/CMSMainTest.php
Required for implementing https://github.com/silverstripe/silverstripe-framework/issues/4938
Relies on https://github.com/silverstripe/silverstripe-framework/pull/5132
> Form Schema

- code/model/SiteTreeFileExtension.php
- code/model/SiteTreeLinkTracking.php
CMS Component of ownership api.
See https://github.com/silverstripe/silverstripe-framework/pull/5095
> API Mark image tracking as owned

- code/reports/BrokenLinksReport.php
- code/reports/SideReport.php
> FIX Use `Controller::join_links()` in Reports

- templates/Includes/CMSMain_Content.ss
> Revert "FIX: Incorrect title attribute on CMS tabs"

- code/forms/SiteTreeURLSegmentField.php
- templates/forms/SiteTreeURLSegmentField.ss
Added readonly version of SiteTreeURLSegmentField, small quality of life thing when a user is looking at readonly data and wants to easily view the frontend of that page.
> Added readonly version of SiteTreeURLSegmentField

- code/model/SiteTree.php
- code/model/SiteTreeFileExtension.php
- code/model/SiteTreeLinkTracking.php
- tests/model/FileLinkTrackingTest.php
- tests/model/FileLinkTrackingTest.yml
- tests/model/SiteTreeHTMLEditorFieldTest.php
- tests/model/SiteTreeLinkTrackingTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/5174
> TinyMCE image shortcodes

- code/model/SiteTreeLinkTracking.php
- tests/model/SiteTreeLinkTrackingTest.php
> FIX Link tracking not escaping `#`

- README.md
> License moved to own file

- code/batchactions/CMSBatchActions.php
- code/controllers/CMSMain.php
- code/model/ErrorPage.php
- code/model/SiteTree.php
- code/model/SiteTreeExtension.php
- tasks/RemoveOrphanedPagesTask.php
- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/bootstrap/SilverStripe/Cms/Test/Behaviour/FixtureContext.php
- tests/controller/AssetAdminTest.php
- tests/controller/CMSBatchActionsTest.php
- tests/controller/CMSMainTest.php
- tests/controller/CMSPageHistoryControllerTest.php
- tests/controller/CMSSiteTreeFilterTest.php
- tests/controller/ContentControllerPermissionsTest.php
- tests/controller/ContentControllerSearchExtensionTest.php
- tests/controller/ContentControllerTest.php
- tests/controller/ModelAsControllerTest.php
- tests/model/ErrorPageFileExtensionTest.php
- tests/model/ErrorPageTest.php
- tests/model/FileLinkTrackingTest.php
- tests/model/SiteTreeActionsTest.php
- tests/model/SiteTreeBacklinksTest.php
- tests/model/SiteTreeBrokenLinksTest.php
- tests/model/SiteTreePermissionsTest.php
- tests/model/SiteTreeTest.php
- tests/model/VirtualPageTest.php
- tests/search/SearchFormTest.php
- tests/tasks/RemoveOrphanedPagesTaskTest.php
Required for https://github.com/silverstripe/silverstripe-framework/pull/5247
> API Support new DataObject::can() signature

- .travis.yml
Requires https://github.com/silverstripe-labs/silverstripe-travis-support/pull/31 to me merged first.
Also, this pull request won't upload artifacts until merged, since secure vars only work on merged branches.
> API Update to use new travis-artifacts

- gulpfile.js
Dependant on https://github.com/silverstripe/silverstripe-framework/pull/5372
> Adapted JS lib references to renamed paths

- code/controllers/CMSMain.php
- code/controllers/SilverStripeNavigator.php
- code/model/RedirectorPage.php
- code/model/SiteTree.php
- tests/controller/SilverStripeNavigatorTest.php
Just some code style improvements I made to CMS while working on https://github.com/silverstripe/silverstripe-framework/pull/5408
> API Changes to CMSPreviewable interface implementors

- code/controllers/AssetAdmin.php
- code/controllers/CMSMain.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/5423
Can be merged with https://github.com/silverstripe/silverstripe-asset-admin/pull/127
> API set menu title without editing transifex masters

- code/search/ContentControllerSearchExtension.php
I think this class was forgotten when DBField namespaces were added to code
> DBField namespace in Search for php7 support

- templates/Includes/Install_successfullyinstalled.ss
Fixes https://github.com/silverstripe/silverstripe-framework/issues/5528
> BUG fix missing install image

- code/controllers/ContentController.php
- code/controllers/ModelAsController.php
- code/controllers/RootURLController.php
Depends on https://github.com/silverstripe/silverstripe-framework/pull/3926
> Fixes relating to Controller cleanup

- code/controllers/CMSMain.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/5532
> BUG Fix rollback page crash

- code/model/RedirectorPage.php
You can also link to external URLs
> DOCS: updated description for redirector page

- templates/Includes/CMSMain_EditForm.ss
CC @clarkepaul 
Correct:
Current:
> BUG Fix missing tabs layout in pages view

- code/model/SiteTree.php
Fixes #1183 (partly)
Requires https://github.com/silverstripe-labs/silverstripe-reports/pull/37 to completely fix it too. :P
> BUG Fix getAbsoluteLiveLink() concatenation

- code/controllers/CMSMain.php
- code/model/SiteTree.php
- code/model/VirtualPage.php
- templates/Includes/CMSMain_ListView.ss
- templates/Includes/CMSMain_TreeView.ss
- tests/model/SiteTreeTest.php
API Revert hack in VirtualPage
API Respect default_cast
To go with https://github.com/silverstripe/silverstripe-framework/pull/5653
> API Respect default_cast

- code/controllers/CMSPageAddController.php
Merge with https://github.com/silverstripe/silverstripe-framework/pull/5806
We need to use DBField casting to override plain-text titles in places where we use HTML markup.
> BUG Fix regressions from https://github.com/silverstripe/silverstripe-framework/pull/5653

- code/controllers/CMSMain.php
Depends upon: https://github.com/silverstripe/silverstripe-framework/pull/3274
> FIX Allow changing admin URLs

- code/controllers/CMSMain.php
See https://github.com/silverstripe/silverstripe-framework/issues/5692#issuecomment-235109269
Closes https://github.com/silverstripe/silverstripe-framework/issues/5692
> Adjust layout of page search form

- client/src/legacy/CMSMain.AddForm.js
- code/controllers/CMSPageAddController.php
- templates/Includes/CMSPageAddController_Content.ss
Supersedes https://github.com/silverstripe/silverstripe-cms/pull/1533 
Requires https://github.com/silverstripe/silverstripe-framework/pull/5826 and https://github.com/silverstripe/silverstripe-framework/pull/5832
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1526
> Add page styles based on the new bootstrap forms

- client/dist/js/AssetAdmin.js
- client/dist/js/CMSMain.AddForm.js
- client/dist/js/CMSMain.EditForm.js
- client/src/legacy/AssetAdmin.js
- code/controllers/AssetAdmin.php
- gulpfile.js
This fixes issues with dist files not being built properly, as per the same fix applied to CMS at https://github.com/silverstripe/silverstripe-framework/commit/6e74b57c36816f3ba763ea0f8fb862306a362506.
I've removed some hacky JS that tried to move the level up button around the dom because it wasn't behaving very well.
> BUG Fix issue with old asset-admin repeating "level up" button

- _config/routes.yml
- tasks/RemoveOrphanedPagesTask.php
Remove redundant Link() override
Required for https://github.com/silverstripe/silverstripe-framework/pull/5854
> BUG Fix incorrect route registration order

- code/model/SiteTree.php
Fixes #1547 
https://github.com/silverstripe/silverstripe-cms/pull/1579/files?w=1
> BUG Fix extra border in page settings

- code/model/VirtualPage.php
- tests/model/VirtualPageTest.php
- tests/model/VirtualPageTest.yml
Dependency of https://github.com/silverstripe/silverstripe-cms/issues/1572
Cleans up some inconsistent controller bootstrapping in virtual page controller.
> API Better behaviour for virtualised controller

- code/Controllers/CMSMain.php
- code/Controllers/CMSPageEditController.php
- code/Controllers/ErrorPageControllerExtension.php
linked to changes made in the following pull requests
https://github.com/silverstripe/silverstripe-framework/pull/5895
https://github.com/silverstripe/silverstripe-asset-admin/pull/223
Also relies on
https://github.com/silverstripe/silverstripe-cms/pull/1586
> Fixes for add to campaign in pages admin

- tests/behat/features/insert-a-link.feature
Requires https://github.com/silverstripe/silverstripe-framework/pull/5945
> Update tests for insert link modal

- code/Controllers/CMSMain.php
- code/Controllers/CMSPageAddController.php
- code/Controllers/CMSPageEditController.php
- code/Controllers/CMSPageHistoryController.php
- code/Controllers/ContentController.php
- code/Controllers/ErrorPageControllerExtension.php
- code/Controllers/ModelAsController.php
- code/Controllers/OldPageRedirector.php
- code/Controllers/RootURLController.php
- code/Forms/SiteTreeURLSegmentField.php
- code/Model/ErrorPage.php
- code/Model/ErrorPage_Controller.php
- code/Model/SiteTreeLinkTracking_Parser.php
- code/Reports/BrokenFilesReport.php
- code/Reports/BrokenLinksReport.php
- code/Reports/BrokenRedirectorPagesReport.php
- code/Reports/BrokenVirtualPagesReport.php
- code/Reports/EmptyPagesReport.php
- code/Reports/RecentlyEditedReport.php
- code/Search/ContentControllerSearchExtension.php
- tests/controller/CMSMainTest.php
- tests/controller/ContentControllerPermissionsTest.php
- tests/controller/ContentControllerTest.php
- tests/model/ErrorPageTest.php
- tests/model/SiteTreePermissionsTest.php
- tests/reports/CmsReportsTest.php
Merge with https://github.com/silverstripe/silverstripe-framework/pull/5974
> Rename SS_ prefixed class names

- tests/behat/features/duplicate-a-page.feature
Test cases for https://github.com/silverstripe/silverstripe-framework/pull/3031
Do not merge before the above, because these fixtures rely on extensions to behat in the above PR.
> Behat test cases for site tree duplication

- code/Controllers/CMSMain.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/5400
> BUG Fix pages level up link

- code/Model/SiteTree.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_EditForm.ss
Merge with https://github.com/silverstripe/silverstripe-framework/pull/6036
> API use new bootstrap button row template

- code/Model/SiteTree.php
@kinglozzer a bit of a cleanup - just want to get an A rating on scrutinizer ;)
> Simplifying SiteTree::getControllerName

- code/Controllers/CMSPageHistoryController.php
- code/Controllers/ContentController.php
- code/Controllers/SilverStripeNavigatorItem.php
- code/Model/ErrorPage.php
- code/Model/SiteTree.php
- code/Model/SiteTreeFileExtension.php
- tests/controller/CMSMainTest.php
- tests/controller/SilverStripeNavigatorTest.php
Thanks @assertchris for the recommendation
> MINOR: Replace get_class($this) with static::class

- code/Controllers/CMSMain.php
- code/Controllers/CMSSiteTreeFilter_PublishedPages.php
- code/Controllers/CMSSiteTreeFilter_StatusDeletedPages.php
- code/Controllers/CMSSiteTreeFilter_StatusDraftPages.php
- code/Controllers/CMSSiteTreeFilter_StatusRemovedFromDraftPages.php
- code/Model/SiteTree.php
- tests/model/FileLinkTrackingTest.php
- tests/model/SiteTreeTest.php
- tests/model/VirtualPageTest.php
CMS PR to go with https://github.com/silverstripe/silverstripe-asset-admin/pull/284
Requires https://github.com/silverstripe/silverstripe-framework/pull/6136
> API Cleaned up versioned status checks

- code/Controllers/CMSSiteTreeFilter.php
- code/Model/SiteTreeLinkTracking.php
- code/Model/VirtualPage.php
CMS changes for https://github.com/silverstripe/silverstripe-framework/pull/6114
> API Update for DataObjectSchema changes

- client/dist/js/bundle.js
- client/src/legacy/CMSPageHistoryController.js
- code/Controllers/CMSMain.php
- code/Controllers/CMSPageAddController.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_EditForm.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PreviewPanel.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Tools.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPageAddController_Content.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPageHistoryController_Tools.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_Content.ss
See https://github.com/silverstripe/silverstripe-framework/issues/6012
Requires https://github.com/silverstripe/silverstripe-framework/pull/6155
> Part 1 of 5, remove JLayout and apply flexbox to pages section (excludes preview)

- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Tools.ss
Requires https://github.com/silverstripe/silverstripe-framework/pull/6189
For more info check out https://github.com/silverstripe/silverstripe-cms/issues/1619
> Split top toolbar for Pages section

- tests/controller/CMSMainTest.php
- tests/model/SiteTreeActionsTest.php
- tests/model/SiteTreeTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/6203
> API Rename _versions table to _Versions

- client/dist/js/bundle.js
- client/src/legacy/CMSMain.Tree.js
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Tools.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_TreeView.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_Content.ss
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1622
Requires https://github.com/silverstripe/silverstripe-framework/pull/6212
> Remove JS from filter height and replace with flexbox

- client/dist/js/bundle.js
- client/src/legacy/CMSMain.js
- code/Controllers/CMSMain.php
- code/Controllers/CMSPagesController.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_ListView.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PageList.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PageList_Sidebar.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Tools.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_TreeView.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_ViewControls.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_Content.ss
Fixes #1645
Requires minor framework PR at https://github.com/silverstripe/silverstripe-framework/pull/6224
> API Update listview / treeview to use pjax instead of deferred loading

- client/dist/js/bundle.js
- client/dist/styles/bundle.css
- client/src/legacy/SiteTreeURLSegmentField.js
- client/src/styles/legacy/_CMSMain.scss
- code/Model/SiteTree.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PageList.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PageList_Sidebar.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_Content.ss
- templates/SilverStripe/CMS/Forms/SiteTreeURLSegmentField.ss
Fixes https://github.com/silverstripe/silverstripe-framework/issues/6164
Requires Framework, CMS, AssetAdmin, Site-config branches of features/4.0/responsive-improvements
> Enhancements for flexbox on smaller screens

- code/Model/SiteTree.php
- tests/model/SiteTreeActionsTest.php
> BUG Prevent archived pages from having add to campaign action

- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1674
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1676
Requires https://github.com/silverstripe/silverstripe-framework/pull/6294
> Safari layout bugs for page actions toolbar and menu toggle area

- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PreviewPanel.ss
Fixes https://github.com/silverstripe/silverstripe-asset-admin/issues/302 
Fixes https://github.com/silverstripe/silverstripe-framework/issues/6297
Fixes https://github.com/silverstripe/silverstripe-framework/issues/6293
Requires:
Framework https://github.com/silverstripe/silverstripe-framework/pull/6303
AssetAdmin https://github.com/silverstripe/silverstripe-asset-admin/pull/303
> Safari layout bugs

- .travis.yml
see https://github.com/silverstripe/silverstripe-framework/pull/6369
> Move travis env vars out of .travis.yml and into travis CI dashboard

- code/controllers/CMSMain.php
- lang/en.yml
This should resolve the majority of behat regressions caused within the last release.
Should fix most issues in this pull request only, but remainder of regressions fixed with https://github.com/silverstripe/silverstripe-framework/pull/6365
> BUG Fix localisation issues in CMS

- code/Controllers/CMSMain.php
- code/Controllers/CMSPageAddController.php
- code/Controllers/CMSPageEditController.php
- code/Model/SiteTree.php
- code/Model/VirtualPage.php
- tests/model/SiteTreeTest.php
- tests/model/VirtualPageTest.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/6356
> API Update to use new form submission handling

- code/Controllers/CMSMain.php
- code/Controllers/ContentController.php
This allows developers to extend SiteTree directly, instead of Page.
> ENHANCEMENT: Use SiteTree instead of Page class in more places.

- code/model/SiteTree.php
> FIX Dont attempt to iterate over null in SiteTree::allowedChildren

- client/dist/js/bundle.js
- client/src/legacy/CMSMain.AddForm.js
- client/src/legacy/CMSMain.EditForm.js
- code/Controllers/CMSMain.php
- code/Controllers/CMSPageAddController.php
- code/Model/SiteTree.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_ViewControls.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_ContentToolActions.ss
- tests/behat/features/duplicate-a-page.feature
- tests/behat/features/edit-a-page.feature
- tests/behat/features/insert-an-image.feature
- tests/behat/features/publish-a-page.feature
- tests/controller/CMSMainTest.php
Also see https://github.com/silverstripe/silverstripe-framework/pull/6434
Requires https://github.com/silverstripe/silverstripe-cms/pull/1699
> Refresh CMS UI buttons to new flat style and bootstrap classes

- code/Model/SiteTree.php
Just making it a little clearer what's going on by changing the variable names and removing some redundant code.
> Clean up code for url-segment checks

- code/Controllers/ContentController.php
> BUG Fix reference to Install_deleteinstallfiles

- .travis.yml
see https://github.com/silverstripe/silverstripe-framework/pull/6573
> CI Check dist files are correctly built

- _config/legacy.yml
> FIX Remap redirector and virtual page class names during build

- code/model/SiteTree.php
> Remove redundant label

- code/Controllers/CMSMain.php
- code/Controllers/ContentController.php
- code/Controllers/RootURLController.php
- code/Model/SiteTree.php
- code/Reports/RecentlyEditedReport.php
- tests/reports/CmsReportsTest.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/6607
> Update CMS for new i18n API

- _config/cache.yml
- code/Controllers/CMSMain.php
- tests/controller/CMSMainTest.php
See https://github.com/silverstripe/silverstripe-framework/issues/6252
> PSR-16 cache

- _config/routes.yml
- code/Controllers/CMSMain.php
- code/Controllers/CMSPageEditController.php
- code/Model/SiteTree.php
- code/Model/VirtualPage.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/6641
> API Upgrade CMS to use new Config API

- client/dist/js/bundle.js
- client/src/legacy/CMSMain.EditForm.js
- package.json
In the page settings section.
So that they will only show when the last option is selected.
Also, fix update package.json for linting and building
Relies on https://github.com/silverstripe/silverstripe-framework/pull/6664 for styling
Fixes https://github.com/silverstripe/silverstripe-cms/pull/1747
> Fix for viewer and editor groups

- .travis.yml
See https://github.com/travis-ci/travis-ci/issues/5323#issuecomment-165536138
Apparently phpunit 4.8 was designed for use with php 5.5, but doesn't work properly with php7.
Once we upgrade to phpunit 5 we can do coverage again on php7.
> BUG Fix PHPUNIT_COVERAGE_TEST by moving to php 5 build

- .travis.yml
- composer.json
See https://github.com/silverstripe/silverstripe-framework/issues/6705#issuecomment-287515832
> Drop PHP 5.5 support

- code/Controllers/CMSPageEditController.php
- code/Model/SiteTree.php
- composer.json
See https://github.com/silverstripe/silverstripe-framework/issues/6735
> Update class namespace for campaign admin

- code/Controllers/CMSMain.php
See https://github.com/silverstripe/silverstripe-framework/issues/6626
> HTML5 Date and Time Fields

- code/model/VirtualPage.php
see https://github.com/silverstripe/silverstripe-framework/pull/6771
> Fixing VirtualPage for php7 patch

- client/dist/js/bundle.js
- client/lang/en.js
- client/lang/src/en.js
- client/src/legacy/CMSMain.EditForm.js
- code/Controllers/CMSMain.php
- lang/en.yml
Issue: https://github.com/silverstripe/silverstripe-framework/issues/6258
> ENHANCEMENT Update archive warning message

- _config/i18n.yml
Requires https://github.com/silverstripe/silverstripe-framework/pull/6706
> Update module_priority to use full module name

- code/controllers/CMSMain.php
- code/controllers/CMSPageHistoryController.php
3.x backport from @tractorcow's work to move page ids into the url
> Make page urls bookmarkable

- code/controllers/CMSMain.php
Fixes issue noted in #1784
@Zauberfisch are you happy with how I've addressed the id / record issue?
> BUG Fix page history / settings forms

- code/Controllers/CMSMain.php
Merge after https://github.com/silverstripe/silverstripe-framework/pull/6883
> Replaced usage of ResetFormAction

- code/Controllers/ModelAsController.php
- code/Controllers/RootURLController.php
Merge together with https://github.com/silverstripe/silverstripe-framework/pull/6884
> Remove APIs with target deprecation of 4.0

- .travis.yml
Move coverage build to script
Update travis node version to 6
Update npm to use yarn for CI
> .travis.yml code cleanup

- .travis.yml
- _config/permissions.yml
- code/Controllers/CMSMain.php
- code/Model/SiteTree.php
- code/Model/VirtualPage.php
- tests/model/SiteTreePermissionsTest.php
- tests/model/SiteTreeTest.php
Refactor permissions into security namespace.
See https://github.com/silverstripe/silverstripe-framework/issues/6063
> API Refactor inherited permissions

- tests/behat/features/insert-a-link.feature
Requires merging silverstripe-admin pull request first
See https://github.com/silverstripe/silverstripe-framework/issues/5947 for more details
Pull requests related:
https://github.com/silverstripe/silverstripe-framework/pull/6914
https://github.com/silverstripe/silverstripe-admin/pull/58
> Fix behat tests for insert link to work with react implementation

- client/dist/js/bundle.js
- client/src/legacy/CMSMain.EditForm.js
Fixes https://github.com/silverstripe/silverstripe-framework/issues/6439
Dependencies
https://github.com/silverstripe/silverstripe-admin/pull/62
https://github.com/silverstripe/silverstripe-framework/pull/6907
> Fix for save and publish buttons shrinking

- code/Model/RedirectorPage.php
> ENHANCEMENT RedirectorPage extensions can now modify fields

- code/Model/SiteTree.php
- code/Model/VirtualPage.php
- code/Search/SearchForm.php
Resolves https://github.com/silverstripe/silverstripe-framework/issues/2842
> Remove create_function implementations, replace with closures

- tests/model/SiteTreeTest.php
See https://github.com/silverstripe/silverstripe-framework/issues/6085
> Remove object class

- .travis.yml
- code/Model/ErrorPage.php
- code/Model/VirtualPage.php
> FIX beforeUpdateCMSFields added to ErrorPage and VirtualPage

- package.json
- webpack.config.js
- yarn.lock
Overlooked removing the temp entries while merging https://github.com/silverstripe/silverstripe-cms/pull/1834
> Fix remove temp external entries

- code/Model/SiteTree.php
- code/Model/SiteTreeLinkTracking.php
- tests/model/SiteTreeLinkTrackingTest.php
Update API usages for https://github.com/silverstripe/silverstripe-framework/pull/6722
> Update HTMLValue and FormField::create_tag usages

- code/Model/SiteTree.php
Issue: https://github.com/silverstripe/silverstripe-admin/issues/101
> More options dropdown label change to icon

- code/Controllers/ContentController.php
- tests/controller/ContentControllerTest.php
Without this you get a "MemberAuthenticator class not found" error.
> FIX Ensure LoginForm on ContentController can load the member authenticator correctly

- code/Model/SiteTree.php
See https://github.com/silverstripe/silverstripe-cms/issues/794
Similar PR for siteconfig: https://github.com/silverstripe/silverstripe-siteconfig/pull/59
> List "view/edit all" groups in group permission field

- _config.php
- code/Controllers/CMSMain.php
- code/Controllers/ContentController.php
This relies on
https://github.com/silverstripe/silverstripe-framework/pull/7065
> NEW: Remove use of MODULE_DIR constants 

- .upgrade.yml
Part of https://github.com/silverstripe/silverstripe-framework/issues/7104
> Update code for upgrader

- code/controllers/CMSMain.php
See https://github.com/silverstripe/silverstripe-cms/issues/1755
> Add archive to list of validation-exempt actions

- _config/i18n.yml
- _config/modules.yml
Required for https://github.com/silverstripe/silverstripe-framework/pull/7154
Main issue: https://github.com/silverstripe/silverstripe-framework/issues/7115
This will probably crash until https://github.com/silverstripe/silverstripe-admin/pull/148 is merged
> API Update module sorting

- code/Controllers/ContentController.php
- code/Model/SiteTree.php
- code/Model/SiteTreeFileExtension.php
Requires https://github.com/silverstripe/silverstripe-framework/pull/7151
> NEW Use injector for creating SSViewer

- code/Model/SiteTree.php
- lang/en.yml
- tests/behat/features/manage-page-permissions.feature
Issue: #1873 
Other PR: https://github.com/silverstripe/silverstripe-siteconfig/issues/67
> NEW Change "only these people" to "only these groups" in permissions

- tests/controller/CMSMainTest.php
- tests/controller/ContentControllerTest.php
- tests/controller/ModelAsControllerTest.php
- tests/controller/RootURLControllerTest.php
- tests/model/SiteTreeTest.php
- tests/model/VirtualPageTest.php
In preparation for https://github.com/silverstripe/silverstripe-framework/issues/6803
> FIX Use merge or set instead of update for config calls

- code/Controllers/CMSMain.php
- code/Controllers/CMSPageHistoryController.php
- code/Controllers/CMSPageSettingsController.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
To fix comment https://github.com/silverstripe/silverstripe-cms/pull/1894#issuecomment-315640838
> FIX Use better inheritance based logic for deciding which active tab to display in edit page

- code/model/VirtualPage.php
- tests/model/VirtualPageTest.php
- tests/model/themes/virtualpagetest/Page.ss
- tests/model/themes/virtualpagetest/VirtualPageTest_ClassA.ss
> FIX Make sure VirtualPage renders correct templates

- code/Model/RedirectorPageController.php
- tests/controller/ContentControllerTest.php
> FIX Allow RedirectorPage to have non-redirected actions, move redirection to index

- code/Forms/InternalLinkFormFactory.php
For https://github.com/silverstripe/silverstripe-admin/issues/53
Depends on https://github.com/silverstripe/silverstripe-framework/pull/7206
> API Use setTitleField to use MenuTitle for selecting internal links

- code/Model/SiteTree.php
- tests/model/SiteTreeTest.php
- tests/model/SiteTreeTest.yml
- tests/model/SiteTreeTest_DataObject.php
> BUGFIX check if parent context is SiteTree instance

- code/Controllers/CMSMain.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_ListView.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PageList.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PageList_Sidebar.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_TreeView.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_TreeView_Deferred.ss
Improves https://github.com/silverstripe/silverstripe-admin/issues/199 (but doesn't completely close this story).
> Restore deferred cms tree loading

- code/Controllers/CMSMain.php
- code/Controllers/LeftAndMainPageIconsExtension.php
- code/Controllers/SilverStripeNavigatorItem.php
- code/Model/SiteTree.php
- code/Model/VirtualPage.php
- tests/php/Controllers/CMSMainTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/7298
> Replace use of Configurable stat() with config()->get(), will be deprecated in future

- code/Controllers/CMSMain.php
Issue: https://github.com/silverstripe/silverstripe-cms/issues/1925
> FIX page not found issue when search in edit page

- code/Controllers/CMSPageAddController.php
- code/Controllers/LeftAndMainPageIconsExtension.php
- code/Model/SiteTree.php
> sanitize namespaced classes for page icon css

- code/controllers/CMSPageAddController.php
- code/controllers/LeftAndMainPageIconsExtension.php
- code/model/SiteTree.php
Backport of https://github.com/silverstripe/silverstripe-cms/pull/1935 for 3.5
> sanitize class names for cms icons

- code/Controllers/CMSMain.php
- code/Controllers/CMSPageHistoryController.php
- code/Controllers/CMSPageSettingsController.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
Fixes #1867 
Screenshot for reference:
> BUG Fix inconsistent breadcrumbs in CMS section

- code/Controllers/CMSPageEditController.php
For https://github.com/silverstripe/silverstripe-admin/issues/161
> Fix campaign form validation errors

- code/Controllers/CMSPageHistoryController.php
- code/Model/SiteTree.php
Issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/625
> FIX Fine-tune button styles

- .eslintrc
- .eslintrc.js
- package.json
- yarn.lock
Requires https://github.com/silverstripe/webpack-config/pull/9 and https://github.com/silverstripe/silverstripe-admin/pull/250
Please see https://github.com/silverstripe/silverstripe-framework/issues/6427 for more details
> Update airbnb rules for linting

- code/Controllers/CMSMain.php
- code/Controllers/CMSPageAddController.php
- code/Controllers/CMSSiteTreeFilter.php
- code/Controllers/CMSSiteTreeFilter_ChangedPages.php
- code/Controllers/CMSSiteTreeFilter_DeletedPages.php
- code/Controllers/CMSSiteTreeFilter_PublishedPages.php
- code/Controllers/CMSSiteTreeFilter_Search.php
- code/Controllers/CMSSiteTreeFilter_StatusDeletedPages.php
- code/Controllers/CMSSiteTreeFilter_StatusDraftPages.php
- code/Controllers/CMSSiteTreeFilter_StatusRemovedFromDraftPages.php
- code/Controllers/ContentController.php
- code/Controllers/LeftAndMainPageIconsExtension.php
- code/Controllers/ModelAsController.php
- code/Controllers/SilverStripeNavigator.php
- code/Model/SiteTree.php
- code/Model/SiteTreeFileExtension.php
- code/Model/SiteTreeFolderExtension.php
- code/Model/SiteTreeLinkTracking_Parser.php
- code/Model/VirtualPage.php
- code/Reports/BrokenFilesReport.php
- code/Reports/BrokenLinksReport.php
- code/Reports/BrokenRedirectorPagesReport.php
- code/Reports/BrokenVirtualPagesReport.php
- code/Tasks/MigrateSiteTreeLinkingTask.php
- code/Tasks/RemoveOrphanedPagesTask.php
- tests/php/Model/SiteTreeFolderExtensionTest.php
- tests/php/Model/SiteTreeFolderExtensionTest.yml
- tests/php/Model/SiteTreeFolderExtensionTest/PageWithFile.php
Add missing unit tests for SiteTreeFolderExtension
Required for https://github.com/silverstripe/silverstripe-framework/pull/7386, but should work in isolation as well.
Parent stories:
- https://github.com/silverstripe/silverstripe-framework/issues/7385
- https://github.com/silverstripe/silverstripe-admin/issues/199
> Update usages of ClassInfo

- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Tools.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_Content.ss
Fixes https://github.com/silverstripe/silverstripe-admin/issues/217
> FIX toolbar title layout

- .eslintrc.js
- .travis.yml
- _config.php
- package.json
Patch for https://github.com/silverstripe/silverstripe-framework/issues/7405
> Fix regressions from vendor modularisation

- templates/Includes/Install_successfullyinstalled.ss
Parent issue https://github.com/silverstripe/silverstripe-framework/issues/7457
> Fix paths in Install_successfullyinstalled.ss

- code/Controllers/CMSMain.php
Parent issue https://github.com/silverstripe/silverstripe-admin/issues/299
> Fix icon urls

- code/model/SiteTree.php
- tests/model/SiteTreeTest.php
Resolves https://github.com/silverstripe/silverstripe-framework/issues/5014
> Move cascading delete to onAfterDelete for SiteTree

- code/Model/SiteTree.php
- tests/php/Model/SiteTreeTest.php
Resolves https://github.com/silverstripe/silverstripe-framework/issues/5014
> Force SiteTree to check in DB before deleting children

- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Tools.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_Content.ss
Please see https://github.com/silverstripe/silverstripe-admin/issues/286 for more details
> BUG Fix up markup and classes to work better with flexbox

- code/Model/SiteTree.php
DOC: Update comment to inform the correct location of the PageIconCSS generation code
> DOC: Update comment to inform the correct location of the PageIconCSS generation code

- code/controllers/CMSMain.php
- javascript/CMSMain.EditForm.js
Fix for https://github.com/silverstripe/silverstripe-cms/issues/1995 in SilverStripe3
> FIX revert to this button after archiving

- .upgrade.yml
Merge after https://github.com/silverstripe/silverstripe-upgrader/pull/44
> Upgrading rules for new inspect/warning capabilities

- code/Search/SearchForm.php
Merge with https://github.com/silverstripe/silverstripe-framework/pull/7545
> BUG Remove usage of deprecated each()

- code/Forms/InternalLinkFormFactory.php
Fixes regression from treedropdownfield changes
> BUG Restore missing '(Choose Page)' text in link insert modal

- .travis.yml
- _config/permissions.yml
- composer.json
Resolves https://github.com/silverstripe/silverstripe-framework/issues/7442
> ENHANCEMENT: Cache inherited permissions

- templates/SilverStripe/CMS/Controllers/Includes/CMSPageAddController_Content.ss
Issue: https://github.com/silverstripe/silverstripe-cms/issues/2055
> Add root breadcrumb title to add page form

- code/Controllers/ContentController.php
Parent issue https://github.com/silverstripe/silverstripe-framework/issues/7419
> Update to support public/ webroot folder

- code/Model/SiteTree.php
- tests/php/Model/SiteTreeTest.php
> ENHANCEMENT Ensure all base folders are excluded

- code/Model/SiteTreeFileFormFactoryExtension.php
Fixes https://github.com/silverstripe/silverstripe-asset-admin/pull/722 behat tests... :/
> BUG Add some exist check for tabsets which may not be there

- .travis.yml
- code/controllers/AssetAdmin.php
- code/controllers/CMSMain.php
- code/controllers/CMSSiteTreeFilter.php
- code/controllers/SilverStripeNavigator.php
Relies on https://github.com/silverstripe/silverstripe-framework/pull/7665
> Add PHP7.2 support

- code/Model/SiteTree.php
> Add missing button styles to restore draft action

- code/Controllers/CMSPageHistoryController.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_notice.ss
> NEW Convert page history notice to use Bootstrap 4 info alert

- code/Controllers/CMSMain.php
- code/Model/SiteTree.php
- lang/en.yml
- tests/behat/features/apply-formatting.feature
- tests/behat/features/duplicate-a-page.feature
- tests/behat/features/edit-a-page.feature
- tests/behat/features/insert-a-link.feature
- tests/behat/features/manage-page-permissions.feature
- tests/behat/features/preview-a-page.feature
- tests/behat/features/publish-a-page.feature
- tests/behat/features/search-for-a-page.feature
Resolves https://github.com/silverstripe/silverstripe-cms/issues/2072
> Replace save draft / save & publish buttons with save, publish

- _config/asset-admin.yml
- code/Model/SiteTreeFileFormFactoryExtension.php
This is to make room for the new feature implemented here https://github.com/silverstripe/silverstripe-admin/pull/427
Please see https://github.com/silverstripe/silverstripe-asset-admin/issues/593 for more details
> Feature remove File extension for backlink tracking

- tests/php/Model/FileLinkTrackingTest.php
- tests/php/Model/SiteTreeBrokenLinksTest.php
- tests/php/Model/SiteTreeFolderExtensionTest.php
- tests/php/Model/SiteTreeHTMLEditorFieldTest.php
So we can use dist version of assets module for testing
> Update reference to TestAssetStore

- code/Model/SiteTree.php
Also see https://github.com/silverstripe/silverstripe-framework/pull/7879
cc @dhensby
> BUG Use correct api to migrate version

- code/Controllers/CMSSiteTreeFilter_ChangedPages.php
- code/Controllers/CMSSiteTreeFilter_DeletedPages.php
- code/Controllers/CMSSiteTreeFilter_PublishedPages.php
- code/Controllers/CMSSiteTreeFilter_Search.php
- code/Controllers/CMSSiteTreeFilter_StatusDeletedPages.php
- code/Controllers/CMSSiteTreeFilter_StatusDraftPages.php
- code/Controllers/CMSSiteTreeFilter_StatusRemovedFromDraftPages.php
- code/Controllers/SilverStripeNavigatorItem.php
- code/Controllers/SilverStripeNavigatorItem_ArchiveLink.php
- code/Controllers/SilverStripeNavigatorItem_LiveLink.php
- code/Controllers/SilverStripeNavigatorItem_StageLink.php
- tests/php/Controllers/CMSSiteTreeFilterTest.php
- tests/php/Controllers/SilverStripeNavigatorTest.php
- tests/php/Controllers/SilverStripeNavigatorTest/UnstagedRecord.php
Parent issue: https://github.com/silverstripe/silverstripe-versioned/issues/115
> BUG Fix behaviour towards versioned but unstagable records

- code/Model/VirtualPage.php
Parent issue https://github.com/silverstripe/silverstripe-errorpage/issues/19
> BUG Fix invalid css classname in virtualpage

- code/Model/SiteTree.php
> BUG Fix InSection failing on non-page controllers

- code/BatchActions/CMSBatchAction_Restore.php
- code/Controllers/CMSSiteTreeFilter.php
- code/Controllers/OldPageRedirector.php
- code/Model/RedirectorPage.php
- code/Model/SiteTree.php
- code/Model/SiteTreeLinkTracking.php
- tests/php/Controllers/CMSBatchActionsTest.php
- tests/php/Controllers/CMSPageHistoryControllerTest.php
- tests/php/Model/SiteTreeBrokenLinksTest.php
- tests/php/Model/SiteTreeTest.php
- tests/php/Model/VirtualPageTest.php
Parent story https://github.com/silverstripe/silverstripe-versioned/issues/93
Fixes regressions in https://github.com/silverstripe/silverstripe-versioned/pull/131
> Update CMS for versioned enhancements

- code/Controllers/CMSMain.php
- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_TreeNode.ss
> adjustment to show Page Type title on SiteTree mouseover

- tests/behat/serve-bootstrap.php
- tests/bootstrap.php
- tests/bootstrap/app.php
This fixes errors such as this https://travis-ci.org/silverstripe/silverstripe-userforms/jobs/364958636 after we switched mysite to app in 4.2.x
Parent issue https://github.com/silverstripe/silverstripe-framework/issues/7946
> FIX Fixture the 'app' dir instead of mysite in unit tests

- code/controllers/CMSMain.php
- code/model/SiteTree.php
- code/model/SiteTreeFileExtension.php
- tests/controller/ContentControllerTest.php
- tests/model/RedirectorPageTest.php
- tests/model/SiteTreePermissionsTest.php
Parent issue https://github.com/silverstripe/silverstripe-versioned/issues/145
> ENHANCEMENT Backport versioned querystring fix

- .travis.yml
Ensure Behat runs on correct Chrome version in Travis
> Make Behat green again, again

- code/controllers/CMSMain.php
- tests/controller/CMSMainTest.php
Resolves https://github.com/silverstripe/silverstripe-framework/issues/8020
> ENHANCEMENT: Remove segmentation from core caches

- code/model/ErrorPage.php
- tests/model/ErrorPageTest.php
- tests/model/ErrorPageTest.yml
Fixes https://github.com/silverstripe/silverstripe-framework/issues/8110
Also merge https://github.com/silverstripe/silverstripe-framework/pull/8122
> BUG Ensure errorpage is built in live mode

- .travis.yml
Parent issue https://github.com/silverstripeltd/open-sourcerers/issues/31
> Target recipe-cms 5.x-dev

- .travis.yml
Parent issue https://github.com/silverstripeltd/open-sourcerers/issues/31
> Update travis to target 4.3.x-dev

- code/Model/SiteTree.php
- lang/en.yml
Fixes https://github.com/silverstripe/silverstripe-framework/issues/4766
> MINOR: Show 'Inherit from site access settings' if there is no parent

- _config/graphql.yml
Resolves: https://github.com/silverstripe/silverstripe-graphql/issues/158
> Add multi-schema support

- _config/routes.yml
> FIX CMS routes are now run after #coreroutes without re-including itself

- code/Controllers/ContentController.php
- use identity operator === to check string
- use single quotes for consistency 
- simplify code using the ternary operator
> use identity operator + code consistency

- code/Controllers/CMSMain.php
Resolves: https://github.com/silverstripe/silverstripe-admin/issues/631
> Set locale on datefields from current user

- code/Controllers/CMSMain.php
Parent issue https://github.com/silverstripe/silverstripe-admin/issues/571
> FIX Improve performance of CMSMain::getArchiveWarningMessage

- tests/behat/features/insert-a-link.feature
Fix tests for https://github.com/silverstripe/silverstripe-admin/pull/637 (they won't pass till this is merged in though)
> Fix 'Insert links into a page' test

- .travis.yml
- code/search/SearchForm.php
(affects v3)
each() and  create_function() are deprecated in PHP7.2 ,
-> I copied the code from the 4 branch - seems to work in my local environment
> PHP7.2 compatibility

- code/Model/SiteTree.php
Fix https://github.com/silverstripe/silverstripe-cms/issues/2276
Tweak the Dependent page GridField to use `GridFieldLazyLoader`.
> MINOR Enable the lazy loading for DependentPages GridField

- code/Controllers/CMSPageHistoryController.php
Fix https://github.com/silverstripe/silverstripe-versioned-admin/issues/67 and https://github.com/silverstripe/silverstripe-cms/issues/2277
> API Deprecate CMSPageHistoryController

- code/Controllers/CMSMain.php
- code/Forms/SiteTreeURLSegmentField.php
- code/Model/SiteTree.php
- tests/php/Controllers/CMSMainTest.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/8424
> FIX Replace usage of Convert JSON methods with json_encode and json_decode

- templates/SilverStripe/CMS/Controllers/Includes/CMSMain_EditForm.ss
- templates/SilverStripe/CMS/Controllers/Includes/CMSPageAddController_Content.ss
- templates/SilverStripe/CMS/Search/Includes/SearchForm.ss
See https://github.com/silverstripe/silverstripe-framework/issues/5674
Requires https://github.com/silverstripe/silverstripe-admin/pull/643
> NEW Use Bootstrap alerts throughout the CMS

- tests/php/Search/DatabaseSearchEngineTest.php
These 2 tests validate that the following bugs have been fixed.
https://github.com/silverstripe/silverstripe-framework/issues/3212
https://github.com/silverstripe/silverstripe-cms/issues/1452
> MINOR: Add tests for some search-form fixes

- code/Forms/InternalLinkFormFactory.php
Requires https://github.com/silverstripe/silverstripe-admin/pull/661
Then closes https://github.com/silverstripe/silverstripe-cms/issues/2273
> NEW Add update extension hooks for LinkFormFactory subclasses

- composer.json
> Update dependencies to have a minimum of SilverStripe 4.3

- code/Controllers/SilverStripeNavigatorItem_LiveLink.php
> Fixing wrong Live-Preview-Link in SilverStripeNavigatorItem_LiveLink

- code/Model/SiteTree.php
- tests/php/Model/SiteTreeTest.php
> FIX Unsaved SiteTree records now return an empty list for DependentPages

- code/Controllers/CMSPageAddController.php
- code/Model/RedirectorPage.php
- code/Model/SiteTree.php
- code/Model/VirtualPage.php
Resolves: https://github.com/silverstripe/silverstripe-admin/issues/574
Relies on: https://github.com/silverstripe/silverstripe-admin/pull/803
> NEW Add font-icon support for site tree

- tests/php/Model/SiteTreeTest.php
This updates the resources dir versus URL segment tests to work in two ways:
* without `extra.resources-dir` configured (e.g. in CMS standalone)
* with `extra.resources-dir` configured (e.g. in installer)
I've made them separate tests with conditional skipping and removed them from the data provider, since they aren't designed for conditional input.
This should fix the `4` branch builds in installer, e.g. https://travis-ci.org/silverstripe/silverstripe-installer/jobs/487760424
> FIX URL segment generation tests for resources dir are now accurate

- code/Controllers/RootURLController.php
Note, I've got no idea behind the logic of should_be_on_root - the change is a best guess based on the fact that `Translatable` doesn't exist in SS4 yet
> Remove core reference to HomePageForDomainExtension 

- tests/php/Controllers/CMSPageHistoryControllerTest.php
> Remove flush from CMSPageHistoryControllerTest

- code/Model/SiteTree.php
- tests/php/Model/SiteTreeTest.php
> FIX: Fixes #2110 added default Title value for saved pages.

- tests/behat/features/insert-a-link.feature
Based on discussions with James Ford, it wasn’t clear that you could
search.
Companion to https://github.com/silverstripe/silverstripe-framework/pull/8766
> MINOR: Change “Choose Page” to “Search or choose Page”

- code/Model/VirtualPage.php
- tests/php/Model/VirtualPageTest.php
Replaces https://github.com/silverstripe/silverstripe-cms/pull/2409 and fixes #2408
> FIX: VirtualPage missing methods from target page (fixes #2408)

- code/Forms/SiteTreeURLSegmentField.php
- code/Model/SiteTree.php
- lang/en.yml
- lang/lv.yml
Updated missed labels to sentence case as per #2361
> Updated “URL Segment” & “Main Content” to sentence case

- code/Controllers/SilverStripeNavigatorItem.php
I feel as though archived should be the same in this context as others rather than having different definitions of what archived means throughout the code
> Keep a more shared understanding of Archived

- code/Controllers/OldPageRedirector.php
Addresses :: https://github.com/silverstripe/silverstripe-cms/issues/2438
> Change self:: to static:: for better extensibility

- code/Model/SiteTree.php
- tests/php/Model/SiteTreeTest.php
> BUGFIX Page Type listed in Page Type dropdown when $can_be_root is false

- CONTRIBUTING.md
Updated Contributing link in intro. Fixed 4 broken (404) links.
> Fixed 5 links in Contributing doc

- code/Controllers/OldPageRedirector.php
Pull request fixin issue #2522
> Fixing issue #2522

- composer.json
- tests/php/Controllers/CMSBatchActionsTest.php
- tests/php/Controllers/CMSMainTest.php
- tests/php/Controllers/ContentControllerSearchExtensionTest.php
- tests/php/Controllers/ContentControllerTest.php
- tests/php/Controllers/ModelAsControllerTest.php
- tests/php/Model/RedirectorPageTest.php
- tests/php/Model/SiteTreeBacklinksTest.php
- tests/php/Model/SiteTreeBrokenLinksTest.php
- tests/php/Model/SiteTreeHTMLEditorFieldTest.php
- tests/php/Model/SiteTreeLinkTrackingTest.php
- tests/php/Model/SiteTreePermissionsTest.php
- tests/php/Model/VirtualPageTest.php
- tests/php/Reports/CmsReportsTest.php
- tests/php/Search/DatabaseSearchEngineTest.php
- tests/php/Search/SearchFormTest.php
- tests/php/Tasks/MigrateSiteTreeLinkingTaskTest.php
- tests/php/Tasks/RemoveOrphanedPagesTaskTest.php
Upgrade to phpunit 8
Depends on https://github.com/silverstripe/silverstripe-admin/pull/1023
> Upgrade to PHPUnit 8

- code/Controllers/CMSMain.php
Please see the commit log for details.
> ENHANCEMENT: Remove unused $controller from lambda function

- tests/php/Search/DatabaseSearchEngineTest.php
- tests/php/Search/SearchFormTest.php
Dependency for https://github.com/silverstripe/silverstripe-framework/pull/9454
> InnoDB FULLTEXT compat in tests

- code/Model/SiteTree.php
> FIX Correct placement of 'Page location' field title

- .travis.yml
- lang/de.yml
- lang/en.yml
- lang/fi.yml
- lang/sl.yml
* https://github.com/silverstripeltd/product-issues/issues/177
> Merge up 4.6 branch + update travis to target x-dev branches

- code/Model/SiteTree.php
https://github.com/silverstripe/silverstripe-cms/issues/2557 - removs FQN if lang != EN on SiteType dropdown in page-settings
> #2557 removs FQN if lang != EN on SiteType dropdown in page-settings

- code/Model/SiteTree.php
- tests/php/Model/SiteTreeTest.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/9617
Needs related PR merged before tests will pass
Related PR https://github.com/silverstripe/silverstripe-framework/pull/9639
Technically not a enhancement PR, though needs to be released as a minor because it will rely on framework 4.7
> FIX Flush embed shortcode provider cache on SiteTree write

- code/Model/SiteTree.php
Minor CSS tweak requested by @sachajudd
> BUG Remove old boostrap 3 CSS class

- code/Controllers/CMSPageHistoryController.php
- code/Tasks/RemoveOrphanedPagesTask.php
Also tidies up some verbose translation keys
Issue: https://github.com/silverstripe/silverstripe-framework/issues/1915
> ENH Replace E_USER_ERROR errors with exceptions

- code/Model/SiteTree.php
Resolves https://github.com/silverstripe/silverstripe-cms/issues/1486
> Add docs to $enforce_strict_hierarchy

- code/Model/SiteTree.php
- lang/en.yml
Resolves: https://github.com/silverstripe/silverstripe-cms/issues/1391
> FIX remove old syntax from meta tag label

- behat.yml
This PR aims to please the Symphony YML gods and fix a a broken build
> BUG Escape % to work with Symhony 4

- code/Controllers/CMSSiteTreeFilter.php
I messed up while merging up and fixing a merge conflict
> BUG Fix parsing error on CMSSiteTreeFilter

- tests/behat/features/view-reports.feature
Behat test broke as part of translations update https://github.com/silverstripe/silverstripe-cms/commit/e23c48618945bc9d510c9a7fc79197c3e1ce4c43
> MNT Fix broken pages with no content behat test

- code/Controllers/CMSMain.php
> FIX: Incorrect method call in savetreenode (fixes #2561)

- _config/graphql.yml
- _graphql/config.yml
- _graphql/models.yml
- code/GraphQL/Resolver.php
See: https://github.com/silverstripe/silverstripe-graphql/pull/329
> NEW: Compliance with new SchemaConfig API

- _config/graphql.yml
See : https://github.com/silverstripe/silverstripe-graphql/pull/327
> NEW compatibility with new stateless plugins

- lang/bg.yml
- lang/cs.yml
- lang/da.yml
- lang/de.yml
- lang/eo.yml
- lang/es.yml
- lang/es_MX.yml
- lang/fi.yml
- lang/fi_FI.yml
- lang/fr.yml
- lang/hr.yml
- lang/it.yml
- lang/nl.yml
- lang/pl.yml
- lang/ru.yml
- lang/sk.yml
- lang/sl.yml
- lang/sv.yml
- tests/behat/features/view-reports.feature
Reverts
https://github.com/silverstripe/silverstripe-cms/commit/88508a243ffe71da7f1b87778e369e768e40c51c
> Revert translation changes

- tests/behat/features/publish-a-page.feature
- tests/behat/src/FixtureContext.php
Issue https://github.com/silverstripe/silverstripe-cms/issues/2641
Targets 4.6, merge up to 4.7 and 4
> MNT Fix archive button behat test

- code/Controllers/CMSMain.php
> FIX undefined variable inChangeSets

- tests/behat/features/duplicate-a-page.feature
Use the new toast notifications PR.
Follow up from https://github.com/silverstripe/silverstripe-admin/issues/504
> BUG Fix Behat test to use new toast notification step

- tests/php/Model/SiteTreeTest.php
Issue https://github.com/silverstripe/silverstripe-admin/issues/1199
Merge this after https://github.com/silverstripe/silverstripe-framework/pull/9998 has been merged
> MNT Update embed shortcode unit test

- tests/php/Controllers/CMSMainTest.php
- tests/php/Model/SiteTreePermissionsTest.php
- tests/php/Search/CMSMainSearchFormTest.php
Issue https://github.com/silverstripe/recipe-cms/issues/47
> MNT Update tests to use logInAs()

- _graphql/config.yml
- code/GraphQL/LinkablePlugin.php
- tests/php/GraphQL/LinkablePluginTest.php
Issue https://github.com/silverstripe/silverstripe-cms/issues/2674
Deserving of a refactor down the track, because this is is really inefficient, but it's a legitimate case for headless apps that want to bulk fetch pages.
> NEW: getByLink plugin allows arrays of links

- tests/behat/features/create-a-page.feature
- tests/behat/features/duplicate-a-page.feature
- tests/behat/features/edit-a-page.feature
- tests/behat/features/sitetree.feature
- tests/behat/src/FixtureContext.php
Issue https://github.com/silverstripeltd/product-issues/issues/473
> MNT Update behat tests

- tests/php/Model/VirtualPageTest.php
Issue https://github.com/silverstripeltd/product-issues/issues/503
Fixes https://app.travis-ci.com/github/silverstripe/silverstripe-cms/jobs/548638033
> MNT Assert string

- code/Model/SiteTreeFileExtension.php
I am just doing this to see if all the tests pass
> ENH: better coding standards

- code/Forms/SiteTreeURLSegmentField.php
- code/Model/SiteTree.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/10250
> ENH Various fixes for PHP 8.1 compatibility

- .codecov.yml
- .github/workflows/ci.yml
- .github/workflows/keepalive.yml
- .travis.yml
- README.md
- phpunit.xml.dist
Issue https://github.com/silverstripeltd/product-issues/issues/570
> MNT Standardise modules
