silverstripe/silverstripe-cms

code/model/VirtualPage.php
This fix ensures that titles are passed through forTemplate() and sanitised correctly in this instance.
=> BUG Correctly sanitise Title

code/model/VirtualPage.php, tests/model/VirtualPageTest.php
I ran into this with a page type like:
```php
class MyPage extends Page {
private static $db = array(
'ExtraContent' => 'HTMLText'
);
}
```
If you create a `VirtualPage` that links to one of an instance of this new page type, `$ExtraContent` in the template won’t work as expected as shortcodes aren’t parsed.
=> FIX: VirtualPages use correct casting for 'virtual' database fields

code/model/SiteTree.php, code/model/SiteTreeLinkTracking.php
- Removed @param/@method references to fields from extensions
- Added @mixin references to extensions (supported by PHPStorm, should also be by Netbeans)
- Fixed incorrect PHPDoc @params and @returns
- Fixed wrapping width on many docblocks
- Added and/or improved method documentation when missing or confusing
- General tweaks and fixes to match latest standards and IDE capabilities
- Fixed typos as found
For the Framework counterpart see https://github.com/silverstripe/silverstripe-framework/pull/3698
=> PHPDoc improvements for SiteTree and SiteTreeLinkTracking

code/model/SiteTreeFileExtension.php
This is an improvement to the UX of asset management, specifically the 'used on' field.
User clicks the 'info' icon...
=> Improve UX of asset management

code/search/ContentControllerSearchExtension.php
It's not currently possible to use injector to customise the SearchForm at the moment due to the way it is instantiated.
This fixes that problem by using the `::create()` function
=> FIX Use SearchForm::create to instantiate SearchForm

tests/controller/CMSMainTest.php
Normally this method is posted via ajax. Leaving out the ajax parameter during mocking of these functions can occasionally cause the `Security::permissionFailure` method to attempt to render a page using the default `Page` class, occasionally breaking due to user-code (especially with custom Requirements).
Basically, this just makes the tests behave a bit more like real life and breaks less unit tests with certain usercode in place.
=> BUG Fix CMSMainTest attempting to render page on Security permission error

code/controllers/CMSSiteTreeFilter.php, templates/Includes/CMSMain_TreeView.ss
Decoupling of CMS / Framework
This feature allows pages matching a custom search to be highlighted in the left hand tree view. This is handy for distinguishing between pages which actually match your search, and those which are simply displayed in order to hold child results.
The class 'CMSSiteTreeFilter' has been refactored out of the core beacuse it's a CMS class, and instead a framework interface 'LeftAndMain_SearchFilter' is used as an abstract api for a search-filterable class.
See https://github.com/silverstripe/silverstripe-framework/pull/4153 for framework component
=> API Enable tree filter highlighting

code/forms/SiteTreeURLSegmentField.php, code/model/SiteTree.php, javascript/CMSMain.EditForm.js, tests/model/SiteTreeTest.php
Replace the hardcoded check for english locale ("new-page") with a localized version. Tested in IE8 and Chrome. See https://github.com/silverstripe/silverstripe-translatable/issues/180
=> Fix auto-setting of URL from localized page titles

code/controllers/CMSMain.php
Previously, when resetting the filter the 'Filtered Tree.' notification would not disappear
It now disappears when clearing the filter.
=> Remove 'Filtered Tree' notification when clearing the filter

css/screen.css, scss/_CMSMain.scss
With the increased space for the site tree in 3.2 and drag/drop icons only appearing on hover they can now be included in the smaller site tree. To be merged with https://github.com/silverstripe/silverstripe-framework/pull/4292
=> Add drag/drop icons to smaller site tree

templates/Includes/CMSPagesController_ContentToolbar.ss
Allows the entire multi-selection button to be clicked rather than just the text and the checkbox
=> Increase click-size of multi-selection button

code/controllers/CMSMain.php
These checks aren't required -- you can duplicate a page regardless of whether you can edit it.
I secretly presume these are required for something, but if not, here's a nice PR to remove them. If they are, why?
=> Fix duplicate not having the correct permission check

code/controllers/AssetAdmin.php, code/controllers/CMSMain.php, css/screen.css, javascript/CMSMain.js, javascript/CMSPageHistoryController.js, lang/en.yml, scss/_AssetAdmin.scss, scss/_CMSMain.scss, templates/Includes/AssetAdmin_Content.ss, templates/Includes/AssetAdmin_Tools.ss, templates/Includes/CMSMain_ListView.ss, templates/Includes/CMSMain_TreeView.ss, templates/Includes/CMSPagesController_Content.ss, templates/Includes/CMSPagesController_ContentToolActions.ss, templates/Includes/CMSPagesController_ContentToolbar.ss, templates/Includes/CMSPagesController_Tools.ss, tests/behat/features/manage-files.feature, tests/behat/features/search-for-a-page.feature
This pull request contains the first part of the UX improvements coming out of the below research:
- http://www.silverstripe.org/blog/using-feedback-to-drive-progress-working-title/
- https://projects.invisionapp.com/share/T53A9E7QA#/screens/83191969
There are UI changes to search filters and bulk actions.
The 'Filters' panel has been removed, and replaced by a search menu, on the top right.
When expanded - you have the same fields as the old filters panel. There is work scheduled to improve the layout of these fields.
The multi-select UI component has been updated and is now called 'bulk actions'.
It is also available in the SiteTree view.
=> UX improvements

code/controllers/CMSSettingsController.php
In 3.2, there are two SiteConfigs present in the CMS:
- CMSSettingsController which extends SiteConfigLeftAndMain
- SiteConfigLeftAndMain as a own module
While SiteConfigLeftAndMain's menu item is removed in _config.php, the controller is still active and will be loaded.
Bug:
- In the CMS click the 'Settings' menu item -- its id is "li#Menu-CMSSettingsController"
- xhr is getting a response from SiteConfigLeftAndMain instead
- LeftAndMain.Menu.updateMenuFromResponse() likes to mark the menu item as selected
- ...but fails to do so because its looking for "#Menu-SiteConfigLeftAndMain" instead
- "li#Menu-CMSSettingsController" stays grey
This PR slightly increases the url_priority value of CMSSettingsController, so CMSSettingsController will be used instead of SiteConfigLeftAndMain.
=> Increase CMSSettingsController:url_priority to suppress SiteConfigLeftAndMain

css/screen.css, javascript/CMSMain.Tree.js, javascript/CMSMain.js, scss/_CMSMain.scss, templates/Includes/AssetAdmin_Content.ss, templates/Includes/CMSMain_Content.ss, templates/Includes/CMSMain_ListView.ss, templates/Includes/CMSMain_Tools.ss, templates/Includes/CMSMain_TreeView.ss, templates/Includes/CMSPagesController_Content.ss, templates/Includes/CMSPagesController_ContentToolActions.ss, tests/behat/features/insert-a-link.feature, tests/behat/features/manage-files.feature, tests/behat/features/search-for-a-page.feature, tests/controller/CMSMainTest.php
Updated view button styles for new layout
Update breadcrumbs for new layout
Included content filters and view buttons in the SiteTree panel.
SiteTree panel collapsed
=> Add three column layout to Page content view

code/reports/BrokenLinksReport.php
The links in the Broken Links Report had extraneous " marks that made
them unusable. This fixes the links.
This patch can and should be merged to 3.2, 3, and master, as well.
=> Correct doubly-escaped " marks

tests/behat/features/insert-an-image.feature
Caused by silverstripe.com redesign. Ideally we'd have a permanent asset hosted there which is clearly marked as a test dependency. @tractorcow If you can be bothered, I'd suggest redeploying ss.org with such an image (e.g. `behat-test-image-do-not-delete.png`).
Or create a hostname placeholder for Behat feature files, so images can be served localhost within the Behat tests, in which case we wouldn't require a network connection to execute Behat.
=> Behat tests hotlinking to non-existant image

.travis.yml, code/controllers/ContentController.php, tests/controller/ContentControllerTest.php
`$arr + $arr` will overwrite values with matching numeric keys whereas `array_merge()` will append them.
The new assertion is a little messy, but I didn’t want to modify the test templates because then I’d have to modify all the other tests!
=> FIX: ContentController::getViewer() not returning all found templates (fixes #1244)

code/controllers/AssetAdmin.php, css/screen.css, scss/_AssetAdmin.scss
for consistent styling of image thumbnails in GridFields. This is a companion fix for https://github.com/silverstripe/silverstripe-framework/pull/4441
=> Moved image thumbnail style rules to Framework

code/controllers/OldPageRedirector.php, tests/controller/ModelAsControllerTest.php
Previously, we would be limited by the way allParams will return 3 parameters at most. This way, we get the full URL.
Keep in mind, this code still needs a clean up, but at least it's not buggy now.
This should probably be merged up as required.
=> MINOR Change how OldPageRedirector gets URLs to fix nested redirects

javascript/CMSMain.EditForm.js, templates/Includes/CMSPagesController_ContentToolActions.ss, templates/forms/SiteTreeURLSegmentField.ss
Now based on `3` branch. Copied from (and supersedes) previous PR https://github.com/silverstripe/silverstripe-cms/pull/1290 which was based on `3.1`
---
This issue (and fix for  #1288) relates to framework issue at https://github.com/silverstripe/silverstripe-framework/issues/3181 and associated pull request: https://github.com/silverstripe/silverstripe-framework/pull/4662
**PLEASE NOTE:** This is a combined fix across both repositories. The actual bug reported in #1288 is addressed in the *other* pull request ([linked above and here](https://github.com/silverstripe/silverstripe-framework/pull/4651)). 
* **CMS:**
* Issue: https://github.com/silverstripe/silverstripe-cms/issues/1288 
* PR: https://github.com/silverstripe/silverstripe-cms/pull/1292 (you are here)
* **Framework:**
* Issue: …
=> FIX (partial) for #1288 where non-submit buttons are being activated on "enter" key press. 

code/model/ErrorPage.php
Addresses #1294. Also ensuring the method follows the parent method definition! Should return `bool`.
**Note:** I'm assuming that `user_error()` is the best route here. I'm not sure how else to register that sort of error.
=> FIX for #1294 to workaround ErrorPage fatal errors (and undefined var) when publishing.

code/controllers/CMSMain.php, tests/controller/CMSMainTest.php
**Note:** This is a duplicate of (and also supersedes) the previous PR #1287 but rebased upon the `3.2` branch instead of `3.1`. 
---
Fix for #586 and possible fix for #736 and relates to https://github.com/kinglozzer/silverstripe-cms/commit/66bfff4d150ce5a6544ff5a21c2644c1469a1761. I believe this addresses bugs relating to removing a newly created draft page which also happens to have validation on it. May also apply to any other validated objects being handled via `CMSForm`.
=> FIX for #586 and possible fix for #736 and relates to #2449: Don't perform validation upon deletion, since it isn't necessary.

code/model/ErrorPage.php
A fix for #1294 on the `3.1` branch since this bug goes way back and affects many versions.
This is a duplicate of https://github.com/silverstripe/silverstripe-cms/pull/1295 to allow for easy merge/fix into `3.1` as well since the code varies too much. Please direct all comments there unless this ticket is completely unnecessary (albeit it does address a *fatal error* so hopefully it is not closed).
=> FIX (v3.1) for #1294 to workaround ErrorPage fatal errors (and undefined var) when publishing.

tests/model/SiteTreeBrokenLinksTest.yml
If https://github.com/silverstripe/silverstripe-framework/pull/4591 is merged, this invalid YAML syntax will cause tests to fail
=> FIX: Remove tab - invalid YAML

_config/cmslogging.yml, code/logging/ErrorPageErrorFormatter.php, code/model/ErrorPage.php, tests/model/ErrorPageTest.php, tests/model/ErrorPageTest.yml
See https://github.com/silverstripe/silverstripe-framework/pull/4680 for the core pull request
CMS-specific errorpage handling has been refactored out of framework module into a separate FriendlyErrorFormatter, which replaces the core framework FriendlyErrorFormatter when cms module is installed.
The ErrorPage static caching has been refactored into the new generated file handling API. However, for the sake of apache error handling (which relies on a physical file at `/assets/error-XXX.html`) an option to continue to write to this specific location (`ErrorPage.enable_static_file`) is included (on by default).
=> Generated files API

tests/controller/CMSMainTest.php, tests/controller/CMSMainTest.yml
Sometimes tests would end up with the default SiteConfig appearing alongside the one specified in the test fixtures.
Additionally, ->post requests which failed were causing Security::LoginForm() to be invoked, causing needless work being done (and potentially breaking if it encountered errors during page rendering).
Using ajax => 1 means that the tests will raise security permission failures appropriately without having to generate rendered error pages.
Some indentation was cleaned up, and a few tests strengthened.
=> BUG Ensure CMSMainTest uses correct siteconfig

code/controllers/ContentController.php
Hi, I've found a bug with unhandled exception from Translatable extension in ContentController.
When you go to page with wrong locale parameter then you'll see 'User Error' on dev environment, but on production you'll see blank page (instead 404 or normal page). 
Try for example: http://youraddress/?locale=en_234
=> Added avoiding unhandled exception from Translatable extension in ContentController

_config/config.yml, code/controllers/ContentController.php, code/controllers/ModelAsController.php, code/model/SiteTree.php, tests/model/SiteTreeTest.php
This moves baked in ErrorPage functionality to an extension, so it can be split out in to an optional module in a subsequent PR. For motivation see https://github.com/silverstripe/silverstripe-framework/issues/4149
=> Decouple ErrorPage

tests/behat/features/insert-a-link.feature
This should fail until https://github.com/silverstripe/silverstripe-framework/pull/4908 is merged
=> Add behat coverage to check that file field is reset when adding links

code/controllers/CMSMain.php, code/controllers/CMSPageEditController.php, templates/Includes/CMSMain_Content.ss
Fixes #1351 and #1358
This looks like old intentional behaviour we don't really want anymore; Selecting "pages" no longer auto-selects a page.
I've also refactored an old update to breadcrumbs which wasn't working with the partial template loading; It should be ok now. ;)
=> BUG prevent "Home page" being selected when no selection was made

code/model/SiteTree.php
=> Adding context parameter to canCreate-check in getClassDropdown

code/model/SiteTree.php, tests/model/SiteTreeTest.php
Yes, I know that `hide_ancestor` is meant to be a string, not boolean! However as the config system can’t warn us about that, this prevents the first page type (usually `Page`) from incorrectly being hidden if it’s set to true (the name _does_ suggest it’s a boolean after all). Plus stricter code = better code, right?
tldr:
```php
array_search(true, array('somestring')) === 0 // meaning that the first class is removed
array_search(true, array('somestring'), true) === false // so we can correctly do nothing
```
=> FIX: Setting hide_ancestor=true causes a random page type to be hidden

code/model/SiteTree.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/4895 (2/2)
Removes border from cms actions
Please note alignment is fixed with https://github.com/silverstripe/silverstripe-framework/pull/4984
before:
after:
=> FIX Borders on CMS Actions

code/controllers/CMSMain.php
"rollback" was added as an exempt action, but isn't actually an action anywhere. The correct name is "doRollback".
=> BUG Use correct formaction for doRollback exemption

code/controllers/AssetAdmin.php
If a folder exists in the DB but not the filesystem, then sometimes editing that in the admin interface will try to show fields from both child-listview and edit-fields in the same interface, although it will not work properly.
Before:
After:
=> BUG Prevent folders deleted on the filesystem from breaking asset interface

code/controllers/CMSMain.php
Was broken at https://github.com/silverstripe/silverstripe-cms/pull/1375/files#diff-be3d9d3389b70ee37e226dd91acf851dL94 (oops :stuck_out_tongue:)
=> Correctly require CMS lang files

code/controllers/CMSMain.php
Can be merged at any time, but no later than when https://github.com/silverstripe/silverstripe-framework/pull/4992 is merged.
This fix essentially removes reliance on the Object::useCustomClass definitions which will be removed.
=> API Remove references to class aliases; Use correct classname

code/batchactions/CMSBatchActions.php, code/controllers/AssetAdmin.php, code/controllers/CMSMain.php, code/controllers/SilverStripeNavigator.php, code/model/SiteTree.php, code/model/SiteTreeFileExtension.php, code/model/SiteTreeLinkTracking.php, code/model/VirtualPage.php, tests/controller/AssetAdminTest.php, tests/controller/AssetAdminTest.yml, tests/controller/CMSBatchActionsTest.php, tests/model/ErrorPageFileExtensionTest.php, tests/model/FileLinkTrackingTest.php, tests/model/SiteTreeBacklinksTest.php, tests/model/SiteTreeBrokenLinksTest.php, tests/model/SiteTreeTest.php, tests/model/VirtualPageTest.php
To be merged after https://github.com/silverstripe/silverstripe-framework/pull/5157
The CMS component of this change actually includes a lot of refactoring; Virtual pages were mostly refactored due to the fundamental changes in the way that related objects must be published under owned versioning.
I have no idea why so many trimmed whitespace ended up in the code... we flushed these ages ago, but I guess they made their way back into the code after merging up from 3 -> master?
=> API Update uses of versioned

css/screen.css, scss/_AssetAdmin.scss
StripThumbnail now provides icon for all file types. To be merged after https://github.com/silverstripe/silverstripe-framework/pull/5186, if accepted
=> Remove redundant CSS

.travis.yml, code/controllers/ContentController.php, code/model/SiteTreeLinkTracking.php, tests/model/VirtualPageTest.php
These changes are necessary for CMS to work with this API breakage:
https://github.com/silverstripe/silverstripe-framework/pull/4551
=> FIX: Changes to support php7 and new DBFields

code/controllers/CMSMain.php
This should really be handled by `FieldList->push()`, but that's too much of a global change for our purpose here (which was generating structured form schemas for React-powered CMS UIs)
/cc @flashbackzoo
=> Ensure all form fields have a form set

.travis.yml
We're not using it for code coverage,
and it's slowing down both composer and phpunit builds.
Recommended by Travis:
https://docs.travis-ci.com/user/speeding-up-the-build/#PHP-optimisations
Merge together with https://github.com/silverstripe/silverstripe-framework/pull/5146
=> Disable xdebug on Travis runs

code/controllers/CMSMain.php
CMSMain::getEditForm wasn't passing the $fields parameter to the parent. The the "Settings" fields we being replaced with the "Content" settings when requesting /admin/pages/settings/show/123345
=> FIX 'Settings' fields being overwritten by 'Content' fields

code/model/ErrorPage.php
Addresses #1447 by simply performing a type-safe check instead of using loose type handling in `if (...)`. Ensuring error message is relevant to the error that actually occurs.
=> FIX for #1447 to ensure proper type-safe checking of file_put_contents() in ErrorPage->writeStaticPage()

composer.json
Fixes https://github.com/silverstripe-labs/silverstripe-fulltextsearch/pull/117
Discovered when testing an install of 3.3 was bringing in 3 branch (alias 3.4) of cms. That cms branch relied on features not present in the 3.3 branch of framework, and busted everything.
=> BUG Correct framework/module dependencies for cms

templates/Includes/CMSMain_Content.ss, templates/Includes/CMSPagesController_Content.ss
Before:
After:
Caused by https://github.com/silverstripe/silverstripe-framework/commit/35e062d9f32df475eb41c78bd709059b417b8b01 updating a CSS class name.
=> Fix font-icon regression on tree view

code/controllers/CMSMain.php, code/model/SiteTree.php
Dependant on https://github.com/silverstripe/silverstripe-framework/pull/5368
=> Add 'Add to campaign' button to pages

code/controllers/CMSPageAddController.php
This will require style changes within framework which I will link to shortly.
Before:
After:
=> Make page steps use the same styles, consistent markup

.tx/config, code/controllers/AssetAdmin.php, code/controllers/CMSMain.php, code/forms/SiteTreeURLSegmentField.php
This fixes alert / confirm boxes that were popping up without text (for
example silverstripe-cms/issues/1476), although ideally we wouldn't
show empty dialog boxes on this sort of error - we'd have some default,
or a way to detect the issue.
=> FIX add_i18n_javascript calls not being updated after JS move

composer.json
See https://github.com/silverstripe/silverstripe-framework/commit/070ae2555b4b6beddec71cd2b9e54057a03e872d
for similar commit when going from 3.1 to 3.2.
See https://github.com/silverstripe/silverstripe-lumberjack/pull/40 for context.
Merge with https://github.com/silverstripe/silverstripe-framework/pull/5561
=> Removed branch alias which should only apply to latest release branch

code/model/SiteTree.php, tests/model/SiteTreeTest.php
This is necessary in cases where extensions apply specific business logic. There is currently no way to make this logic apply to admins.
Re-raised https://github.com/silverstripe/silverstripe-cms/pull/1507 on master branch.
=> API Allow extensions to influence can* methods

code/controllers/OldPageRedirector.php
Fixes #1045
Avoid redirecting to the same URL.
I've tested this with silverstripe sites in the root folder and a subfolder and it works as expected.
=> Prevent OldPageRedirector looping infinitely

code/model/SiteTree.php, tests/model/SiteTreeTest.php
Merge this before accepting https://github.com/silverstripe-australia/silverstripe-advancedworkflow/pull/261
At the moment onBeforeDuplicate is run on both the original and the duplicate.
This corrects the behaviour to run only on the duplicate, and have it pass in the original to the first parameter consistently.
dataobject implements as:
```php
public function duplicate($doWrite = true) {
$className = $this->class;
$clone = new $className( $this->toMap(), false, $this->model );
$clone->ID = 0;
$clone->invokeWithExtensions('onBeforeDuplicate', $this, $doWrite);
if($doWrite) {
$clone->write();
$this->duplicateManyManyRelations($this, $clone);
}
$clone->invokeWithExtensions('onAfterDuplicate', $this, $doWrite);
return $clone;
}
```
=> API Cleanup inconsistent SiteTree::duplicate API

code/controllers/CMSPageHistoryController.php
MINOR Boyscouting: Addition of missing braces, default return and missing types in @return annotation.
=> FIX: Fixes #1054 By preventing errors in the CMS _only_.

code/model/SiteTree.php, tests/model/SiteTreeTest.php
* Resolves #1553
This change could probably be back merged into earlier 3.x versions too.
=> FIX do not show HiddenClass pages in allowed children

code/controllers/SilverStripeNavigator.php
Fixes #1557
Fixes https://github.com/tractorcow/silverstripe-fluent/issues/219
Also fixes excessive line length, incorrect html attribute escaping (i.e. none), trailing whitespaces, incorrect PHPDoc, missing parent::__construct
=> BUG Fix link concatenation in SilverStripeNavigator

templates/CMSPageHistoryController_versions.ss
I've rebased this work against the new bootstrap form branch https://github.com/silverstripe/silverstripe-cms/pull/1530 so that PR should be accepted first.
Requires https://github.com/silverstripe/silverstripe-framework/pull/5724
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1527
After:
=> History panel forms markup add extra table header class

.travis.yml, code/controllers/AssetAdmin.php, code/controllers/CMSFileAddController.php
Trying to navigate directly to the edit view of a file by URL would fail if a folder other than the file’s parent was held in session data, as it would take precedence over falsey but valid values such as 0 or null. Additionally, breadcrumbs would be missing if navigating directly to a file edit URL without navigating through the gridfield first. Storage of current folder ID in session retained for backwards compatibility, but reliance on it has been removed.
Behat test will fail without companion fix at https://github.com/silverstripe/silverstripe-framework/pull/5848
=> FIX Direct edit file by URL

code/Controllers/ErrorPageControllerExtension.php
This would allow for error messages to passed easily when an ajax call is made instead of a full form submit.
=> API: Add checker for Ajax calls so error page is not returned

code/Controllers/CMSMain.php, tests/controller/CMSMainTest.php
Fixes #1210
See https://github.com/silverstripe/silverstripe-framework/pull/5950 for probably-not-necessary cleanup in core to validate at the DataObject level.
=> BUG Ensure changes in class write to an instance of the new class

templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PreviewPanel.ss
Ensures that preview area is only loaded for sections which support preview. Originally it was designed as a CMS-wide feature, but it was never utilised outside of CMSMain.
Merge this first, and then https://github.com/silverstripe/silverstripe-framework/pull/5994.
=> API Move preview template to cms section

.eslintrc
This caught us out recently where code did a strict type check for `myVar === undefined`.
The var was defined as `let myVar;`, without a value - so the check returned false (it's `null`).
To avoid this situation, we've decided to enforce declarations with values.
Note that preference should be given to single, immutable assignments via const where possible.
See http://eslint.org/docs/rules/init-declarations
=> Enforce JS var declaration with value

templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss
This is to help when legacy styling may be taken out.
=> Add Bootstrap4 classes to tabs

code/Model/SiteTreeFileExtension.php, lang/en.yml, templates/SilverStripe/CMS/Model/Includes/SiteTreeFileExtension_description.ss
This is a temporary work around to populate the Usage tab for Files and Images, until https://github.com/silverstripe/silverstripe-asset-admin/issues/251 is addressed
=> Moved Backlink list/table to SS Template

code/Controllers/CMSPageHistoryController.php, code/Controllers/ModelAsController.php, code/Model/ErrorPage.php, code/Model/SiteTree.php
To reduce dependence on a ‘god ancestor’ class we should use get_class()
instead.
=> FIX: Remove references to Object::$class

code/model/SiteTree.php, tests/model/SiteTreeTest.php
This fixes an issue where pages duplicated with their children cause the new child pages to all have the same Sort value causing the child pages to jump around on save.
=> FIX Sort order for duplicated child pages is now retained

code/controllers/CMSPageHistoryController.php
When viewing history comparisons in the CMS the notice would say that you're comparing the current live version to `1` rather than the two versions you'd selected.
=> FIX History controller now shows right comparison versions

code/Controllers/CMSPageHistoryController.php
Fixes https://github.com/silverstripe/silverstripe-cms/issues/1612
I think this might be caused by a deeper bug in `ViewableData_Customised`, but it's abstract for me to get into. Maybe @tractorcow would be interested
=> Fix double nested alert message

_config.php
This pull request fixes an issue found in SilverStripe 4 Alpha 3 where the cms would hard crash on windows because the CMS_DIR constant was being set containing a backslash. This seems to be caused by the trim call having a hard coded forward slash.
=> BUGFIX: Fixed issue on windows where the CMS_DIR constant would be set containing a backslash

.travis.yml, phpunit.xml.dist, tests/controller/ContentControllerTest.php, tests/model/SiteTreeTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/6089
Note that the `phpunit.xml.dist` won't apply until we make builds run without `travis-support` (out of scope for this PR). Once that's resolved it'll automatically pick up the PHPUnit defaults set here.
=> Code Coverage via CodeCov.io

code/model/ErrorPage.php, tests/model/ErrorPageTest.php
would end up with the error page response code, causing them to not work. This code only looks to be causing issues from what I can see.
An example is an autocomplete that is populated using a method on page controller. The moment you end up on a 404 error page, the autocomplete will attempt to populate and end up with a 404 response.
---
The only thing I noticed when removing this, is that hitting an error page **directly** ends up with a 200 response code (as opposed to the error page response code). Which is technically correct though, since this page **was** actually found. Hitting a URL that doesn't exist, however, continues to throw a 404.
The current state is quite nasty, and I've noticed it affecting a number of production sites, so it would be good to get this bug corrected …
=> Correcting an issue where page controller methods

javascript/CMSMain.AddForm.js
Pretty simple fix, it was trying to get SiteTree hints for “SiteTree” instead of “Root” when no parent page is selected (so it _should_ be trying to get the hints for “Root”).
=> Ensure we have a ParentID before trying to limit children by page type (fixes #1273)

code/Model/RedirectorPage.php
RedirectorPage has a requirement on a JS file `cms/client/dist/js/RedirectorPage.js` which since has been moved over to `cms/client/dist/js/bundle.js` causing an `InvalidArgumentException`
Removing it fixes the exception, and causes no other issues:
=> Removed dud Requirements breaking the RedirectorPage

.upgrade.yml, code/Model/ErrorPageController.php, code/Model/RedirectorPageController.php, code/Model/SiteTree.php, tests/bootstrap/fixtures/Page.php.fixture, tests/controller/ContentControllerTest.php, tests/model/RedirectorPageTest.php, tests/model/SiteTreeTest.php, tests/model/VirtualPageTest.php
This pull request changes the default controller class lookup from `My_Controller` to `MyController`. It still supports `My_Controller` loading, however it will issue a deprecation notice from 4.0.0 onwards.
Issue: silverstripe/silverstripe-framework#6403
Blocks: silverstripe/silverstripe-framework#6446
=> API Allow controller discovery without underscore (PSR-2 compliance)

code/Controllers/CMSMain.php, code/Controllers/ContentController.php, code/Controllers/ModelAsController.php, code/Model/RedirectorPageController.php, code/Tasks/RemoveOrphanedPagesTask.php
`Controller` has had it's `init()` method changed to `protected`, updating `Controller` subclasses in CMS to follow suit.
=> Changed init() visibility to protected

client/src/legacy/CMSMain.AddForm.js
When there's no templates that can be added in the root /admin/pages/add/ hits a JS error and never completes loading
=> FIX: Javascript .addAttr() doesn't exist

code/Controllers/CMSMain.php, code/Controllers/CMSPageEditController.php, code/Controllers/CMSPageHistoryController.php, code/Controllers/CMSPageSettingsController.php, code/Controllers/ContentController.php, code/Model/SiteTree.php, lang/de.yml, lang/en.yml, tests/model/SiteTreeTest.php
Required for https://github.com/silverstripe/silverstripe-framework/pull/6558
=> Upgrade cms for new i18n backend

code/controllers/CMSFileAddController.php
When uploading files and the ASSETS_DIR directory is a subdirectory, for example `assets/site1`. The slash was being included as a part of the regex statement making it invalid. Adding a preg_quote command has escaped special characters as well as the forward slash.
=> Fix error when uploading file and ASSETS_DIR is a subdirectory

_config.php, _config/config.yml, code/Model/SiteTree.php, code/Model/SiteTreeLinkTracking.php, tests/model/SiteTreeBrokenLinksTest.php, tests/model/SiteTreeTest.php
It turns out CMS relied on FIRST_SET for allowedChildren()
In a separate commit I've done some unit test class cleanup (rewrite from strings -> class constants, and other formatting improvements).
=> FIX Config regressions

code/Controllers/CMSPageHistoryController.php, tests/controller/CMSPageHistoryControllerTest.php
so the fields no longer escape the `<ins>` and `<del>` tags injected by the Differencer in the History view for pages.
Original issue https://github.com/silverstripe/silverstripe-cms/issues/1746
Also added some unit tests for this.
=> Fix history comparison fields

code/Model/VirtualPage.php
Fix non_virtual_fields and initially_copied_fields being ignored in classes that extent VirtualPage
=> Fix non_virtual_fields being ignored

code/Controllers/CMSMain.php, code/Controllers/SilverStripeNavigator.php, code/Controllers/SilverStripeNavigatorItem.php, code/Model/SiteTree.php, composer.json
Requires https://github.com/silverstripe/silverstripe-framework/pull/6695
We had to move CMSPreviewable to framework module, as otherwise framework classes couldn't inherit it without directly requiring admin module (undesirable).
=> Add dependency on admin module

.travis.yml
We only care about the dist files. If we diff in the root folder,
we'll get false positives on composer.json changes.
See https://travis-ci.org/silverstripe/silverstripe-cms/jobs/215796957
=> Only git-diff files in client folder

code/Controllers/CMSMain.php, code/Model/SiteTree.php
This prevents clash with db Description fields for pages.
private static property is left unchanged.
Fixes #1733
=> API Rename SiteTree::description() to SiteTree::classDescription()

.upgrade.yml, code/Controllers/CMSMain.php, code/Controllers/CMSPageAddController.php, code/Controllers/CMSPageHistoryController.php, code/Controllers/CMSSiteTreeFilter.php, code/Controllers/CMSTreeNode.php, lang/de.yml, templates/SilverStripe/CMS/Controllers/Includes/CMSTreeNode.ss, tests/controller/CMSTreeTest.php, tests/controller/CMSTreeTest.yml
Fixes #1510, meaning that we can now use formfield-actions in react sections.
Refactor tree operations into CMSMain; Increases complexity of CMSMain (unfortunately), but simplifies LeftAndMain by removing all tree-handling logic.
Cleanup of getEditForm() and various other aging code blocks.
Note: @timkung has been working on a 3.x version at https://github.com/silverstripe/silverstripe-cms/pull/1784
=> BUG Ensure all CMS forms include full ID / VersionID in path

.gitignore
This was causing the https://github.com/silverstripe/silverstripe-cms/tree/master/code/Reports folder to appear as ignored (in some IDE). Modules aren't normally installed within CMS dir, so removing these from gitignore.
=> Remove extraneous gitignore declarations

tests/model/SiteTreeTest.php
It appears that a change to the translation strings has caused this test to fail.
I've also rearranged the parameters to be correct.
=> FIX intl test

.gitattributes
With the current export-ignore in place, behat.yml is deleted when installed within framework, breaking integration tests when framework runs BEHAT_TEST = cms.
=> Prevent installation from removing behat.yml

webpack-dev.config.js
They're not being used and they're breaking things, e.g. `ExtractTextPlugin` and creating unused common chunks bundles e.g. `client/dist/js/vendor.js`
=> BUGFIX: Get rid of special dev webpack plugins

client/dist/js/bundle.js, client/src/legacy/CMSMain.EditForm.js
Parent issue: https://github.com/silverstripe/silverstripe-cms/issues/1714
The "Who can view this" UI is used in multiple admin modules. Moved behaviour to `silverstripe-admin`.
=> Move who-can-view toggle to Admin module

_config/adminpanels.yml, _config/cache.yml, _config/cmslogging.yml, _config/config.yml, _config/injector.yml, code/Model/ErrorPage.php, code/Model/SiteTreeLinkTracking.php, tests/model/ErrorPageTest.php
See https://github.com/silverstripe/silverstripe-framework/issues/6642
Requires certain framework changes to be merged first, especially the logging service name.
Includes some yml and ErrorPage cleanup.
=> API Rename services to match FQN of interface / classes

code/model/SiteTree.php
for users who can delete, but not unpublish, they should be able to delete draft pages that they’ve created.
Old code used to unpublish even if the page wasn’t published, which meant users who couldn’t publish, also could delete draft pages. They could create draft pages, but not delete them.
=> fixing doArchive

code/model/SiteTree.php, tests/model/SiteTreePermissionsTest.php
=> FIX Issue recursion when parent/child records are swapped in SiteTree

code/model/SiteTree.php
Children of the site tree are no longer listed only for the purpose of counting them. count($this->Children()) creates an array list of children which has serious performance consequences if there are lot of children present. On the other hand $this->numChildren() runs a count query which is much faster and eats less memory.
=> Count children time / memory issues fix

code/Controllers/CMSMain.php, code/Controllers/CMSPageAddController.php, code/Controllers/ContentController.php, code/Model/SiteTree.php, composer.json, tests/controller/CMSMainTest.php, tests/controller/SilverStripeNavigatorTest.php, tests/model/ErrorPageFileExtensionTest.php, tests/model/SiteTreeActionsTest.php, tests/model/SiteTreePermissionsTest.php, tests/model/SiteTreeTest.php, tests/search/SearchFormTest.php
- Move Member::currentUser() to Security::getCurrentUser()
Composer.json temporarily changed for tests to run
=> [WIP] Make CMS Compatible with Authentication Refactor work

code/Controllers/CMSPageAddController.php
`addForm` function receives both POSTs and GETs.  Set the form's `strictFormMethodCheck` to false to avoid `405 Method Not Allowed` error responses.  Issue #1846.
=> Bugfix: SS4 Right click, add page fails

tests/model/SiteTreeTest.php
See https://github.com/silverstripe/silverstripe-framework/pull/7083
=> FIX: Test updates to comply with DataObject::get_one cahnge

code/Model/SiteTree.php
Limits added to collateDescendants() to ensure reasonable performance with thousands of pages.
This change set fixes a performance issue with the CMS. I tested this on a site with ~4000 pages. Current version of the code iterates of all pages which is unusable for such site.
This change set is related to wider performance boost on SilverStripe 4. Please see following PRs:
https://github.com/silverstripe/silverstripe-framework/pull/7129
https://github.com/silverstripe/silverstripe-lumberjack/pull/57
=> Limits added to collateDescendants

templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_ContentToolActions.ss
Partial fix for https://github.com/silverstripe/silverstripe-admin/pull/28 which adds a missing class to toolbars.
Can be merged independently of https://github.com/silverstripe/silverstripe-admin/pull/28
=> Add missing class to toolbar

code/Controllers/CMSMain.php, templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Content.ss, tests/behat/features/edit-a-page.feature
Resolves #1883 and resolves #1887
=> FIX Ensure tab states are reflected when switching on page edit screen

tests/controller/CMSMainTest.php
The tests are failing since the version provider is an injected dependency, switch CMSMain instances to be created with the injector in the CMSMain tests
Related issue: https://github.com/silverstripe/silverstripe-admin/pull/157
=> FIX Use injection for CMSMain in tests

code/Controllers/CMSMain.php
=> Remove sprintf translations in CMSMain in favour of named parameters

code/Model/SiteTree.php, code/Model/VirtualPage.php, tests/model/SiteTreeBrokenLinksTest.php, tests/model/VirtualPageTest.php
Fixes broken CMS tests on https://github.com/silverstripe/silverstripe-framework/pull/7257, but neither will pass in isolation.
Parent story: https://github.com/silverstripe/silverstripe-versioned/issues/23
=> API Virtual pages now respect cascade_deletes on source page

code/Model/SiteTree.php, tests/php/Model/SiteTreeTest.php, tests/php/Model/SiteTreeTest_ExtensionA.php, tests/php/Model/SiteTreeTest_ExtensionB.php
This is necessary to allow post-baseurl applied links to be modified.
Useful for modules such as subsites / fluent which may need to prepend domain names.
=> API Allow SiteTree::Link to be extended

code/Controllers/CMSMain.php
Fixes #1949 and #1939
Previously I'd added in the page ID to force the "current" page and avoid a session access, but this broke the caching of treeview so it's been reverted.
=> BUG Prevent treeview loading repeatedly on each page edit form

code/Controllers/CMSPageEditController.php
The existing code will overwrite any `$config['form']` values with its own. This change merges them instead.
Note - current state returns AddToCampaignForm and editorInternalLink. With this change it also returns EditorEmailLink and EditorExternalLink
=> FIX Ensure client config merging includes existing parent "form" attributes

code/model/SiteTree.php
Removing this class hides the page type icons in the “unexpanded” TreeDropdownField (they still show up when you expand it), restoring the old behaviour.
Looks like a regression from https://github.com/silverstripe/silverstripe-cms/pull/1936
=> Fix: TreeDropdownField showing broken page icons (fixes silverstripe/framework#7420)

code/controllers/CMSFileAddController.php
Enable UploadField overwriteWarning
```yaml
Upload:
replaceFile: true
UploadField:
defaultConfig:
overwriteWarning: true
```
In assets admin, when you upload files with same name in non-root folder, it just replaces the file and there is no overwrite warning message.
This fix will let CMSFileAddController know the current folder when 'fileexists' AJAX request is called.
=> BUG UploadField overwriteWarning isn't working in AssetAdmin

code/Model/SiteTreeLinkTracking_Parser.php, tests/php/Model/SiteTreeLinkTrackingTest.php
Prevents calling Director::makeRelative() on links that don't belong to this site.
Required for https://github.com/silverstripe/silverstripe-framework/pull/7520
Parent issue https://github.com/silverstripe/silverstripe-framework/issues/7492
=> BUG Safely check for is_site_url before parsing a shortcode

.travis.yml
Might fix https://github.com/silverstripe/silverstripe-cms/issues/2036 by minimising differences between broken CMS build and working framework build.
=> Update .travis.yml in line with framework .travis.yml

code/Controllers/LeftAndMainPageIconsExtension.php, code/Model/SiteTree.php
Fixes #2034
Code was getting the icon twice, both in SiteTree & LeftAndMainPageIconsExtenstion.
Now just uses `SiteTree::getPageIconURL()`
Tweaked to use `sprintf` instead of double quotes
=> Issue-2034: Fix for Page icons using data urls

code/Controllers/CMSMain.php
This speeds the AJAX request from 3.81s to 1.7s
Also should only return the top level pages otherwise its just assuming and thus wasting resources
This also allows it to be fully controlled via config whereas for the `/admin/pages/treeview` AJAX call it was defaulting to 30 as no parameter was passed
=> Make `CMSMain::getSiteTreeFor()` default to `null` nodeCount

code/Controllers/ContentController.php, code/Model/VirtualPage.php, tests/php/Model/VirtualPageTest.php, tests/php/Model/themes/virtualpagetest/templates/SilverStripe/CMS/Tests/Model/VirtualPageTest_ClassB.ss
Requires: https://github.com/silverstripe/silverstripe-framework/pull/7668#discussion_r154855427
Two commits/fixes here.
First one (ref. `refreshFromCopied()`) is because when you write a `VirtualPage` for the first time, `SiteTree::onBeforeWrite()` will check for a duplicate URL and fix it, but then `refreshFromCopied()` was running _afterwards_ and overwriting it with the target page’s URL.
Second one is the actual fix for #2039. Introduces a new API `SiteTree::getViewerTemplates()` which I’m happy to take feedback on, I just can’t see any way of solving this without that extra API (or hardcoded checks for `instanceof VirtualPage` in `ContentController`).
Given that this is a bugfix (and it severely impacts the usefulness of `VirtualPage`) I think a new API is acceptable in a patch …
=> FIX: VirtualPage not using target page's template (fixes #2039)

code/Model/SiteTree.php
This allows for the field to be overridden using the injector e.g.
```yml
SilverStripe\Core\Injector\Injector:
SilverStripe\Forms\HTMLEditor\HTMLEditorField:
class: SilverStripers\markdown\forms\MarkdownEditorField
```
=> Change `new HTMLEditorField` to `HTMLEditorField::Create`

_config/cache.yml, _config/permissions.yml, code/Controllers/CMSMain.php, code/Model/SiteTree.php, code/Model/VirtualPage.php, tests/php/Controllers/CMSMainTest.php, tests/php/Model/SiteTreeTest.php
Resolves https://github.com/silverstripe/silverstripe-cms/issues/1977
(-) CMSMain cache
(-) SiteTree cache
* 15.5s wall time
* 32.1MB memory
* 1.45s response time
(+) CMSMain cache
(-) SiteTree cache
* 15.3s wal
* 30.6MB
* 1.2s
(+) CMSMain cache
(+) SiteTree cache
* 7.5s
* 0.9s
* 31MB
=> ENHANCEMENT: Cache canCreate in CMSMain

README.md
Primarily because the "issue reporting guidelines" link was broken.
=> DOCS Update documentation links, remove forums link and helpful robot badge

javascript/CMSPageHistoryController.js
On pages with a large amount of versions was getting extremely bad performance when clicking on the page history tab.  After the page loaded, javascript was causing the page to be unresponsive for a very long time, up to 120 seconds in chrome.
The issue boiled down to element.compareDocumentPosition being erroneously called a huge number of times by jQuery, like it was getting totally confused by itself
Have updated to use regular JS instead of jQuery for a .removeClass call, and make another jQuery selector more explicit
=> Update page history javascript to fix big performance issue

code/Controllers/CMSPageHistoryController.php, templates/SilverStripe/CMS/Controllers/Includes/CMSPageHistoryController_versions.ss
Related: https://github.com/silverstripe/silverstripe-framework/issues/7663 (implements 5.0 changes only)
Ensures CMS page history section works after https://github.com/silverstripe/silverstripe-versioned/pull/81 is merged.
=> API Update usage of Versioned::allVersions()

code/Model/SiteTree.php
Related issue: https://github.com/silverstripe/silverstripe-admin/issues/201
cc @sachajudd
Before:
After:
=> NEW Use Bootstrap alerts instead of legacy message classes for install.php warning

code/Controllers/CMSPageHistoryController.php
`$this` is automatically bound to closures after PHP 5.3 so we don't need to do this any more (minimum PHP 5.6 on SS4).
=> MINOR Stop aliasing $this in history controller callbacks

code/Controllers/CMSMain.php, code/Controllers/CMSPagesController.php
Part of silverstripe/silverstripe-admin#439
Allows, for example, user code to push a badge in the "Extra" attribute for the last breadcrumbs link.
=> NEW Add extension point to CMSMain::Breadcrumbs

code/search/ContentControllerSearchExtension.php
Relates to https://github.com/silverstripe/silverstripe-cms/issues/2125
=> FIX: Remove SearchForm results() function from allowed_actions

code/Controllers/ContentController.php
Fix #2130
`SilverStripeNavigator` needs to be cast as html otherwise it renders as escaped html
=> FIX Correct SilverStripeNavigator correctly in templates

code/Model/SiteTree.php
Remove the Restore button if there's no where viable to restore the page to.
=> Bugfix: Don't offer to restore to root if can_be_root is false

tests/php/Controllers/ModelAsControllerTest.php, tests/php/Model/SiteTreeTest.php
We've changed default config or unloaded extensions that are causing tests to fail. This fixes those tests, I guess other devs have their own instances of this too.
=> Tests assume default config can fail

code/model/RedirectorPage.php
This prevents the following warning:
`Fatal error: Declaration of RedirectorPage::Link() must be compatible with SiteTree::Link($action = NULL) in /vagrant/project/cms/code/model/RedirectorPage.php on line 0` in PHP 7.2
=> FIX Make RedirectorPage::Link compatible with SiteTree::Link

code/Controllers/ContentController.php
`deleteinstallfiles` doesn't currently work because it expect the install files to be in the root.
I've also removes some old SS2.4 install legacy files from the list of files to check and added `install-frameworkmissing.html`
* #2166
=> Adjust `ContentController::deleteinstallfiles()` to use PUBLIC_PATH.

code/model/SiteTree.php
Related to silverstripe/silverstripe-framework#8160 .
The PR corrects SiteTree where it attempts to fetch the site tree record from the current stage using `get_one_by_stage`. In the case of tests the current stage is often null and `get_one_by_stage` expects a valid stage. Getting the site tree record directly will fetch for the appropriate stage.
=> FIX Remove blind reliance on current versioning stage being valid

_config/scripts.yml
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7996
Alternative solution to moving CMS components to admin module (https://github.com/silverstripe/silverstripe-cms/pull/2176)
=> BUG Fix CMS components failing to register on other CMS sections

tests/php/Model/VirtualPageTest.php
The updated class name references are necessary to allow three Virtual Page tests that are part of the cwp-recipe-cms to pass.
=> Update class references and array syntax in VirtualPageTest

tests/php/Model/SiteTreeTest.php, tests/php/Search/SearchFormTest.php
Updates the class references in the illegal extensions section. Replaces Translatable with Fluent. Also updates the array syntax
=> Update illegal extensions

code/controllers/CMSMain.php, tests/controller/CMSMainTest.php
See issue:
https://github.com/silverstripe/silverstripe-cms/issues/2194
- Added missing check for publishing rights.
- Fixed class change as it was treating ClassName attrs in reverse order (going new->to->old, rather than old->to->new).
=> [Fix] CMSMain::save - class change & publish perms

code/Forms/AnchorSelectorField.php, code/Model/SiteTree.php
The current AnchorSelectorField only takes into account a pages `Content` field. This causes issues with modules such as Elemental which don't use `$Content`.
Moves the anchor extraction functionality to `SiteTree::getAnchorsOnPage` function which then defines an extension hook to modify.
=> NEW add SiteTree::updateAnchorsOnPage() for defining content anchors

code/Model/SiteTree.php, tests/php/Model/SiteTreeTest.php
Currently you can do this by overriding the `getControllerName()` method but this feels more idiomatic. Means that you can more easily do things like put your controllers in a `MySite\Control` namespace and have your pages in `Mysite\Model`. Additionally saves having to do the while loop if you don't have to - could be an aim to have this as required by 5.0 to reduce unnecessary cycles (and ✨ magic ✨ ).
=> add controller_name config var to SiteTree for easier override

_config/routes.yml
Fixes #2225 
By separating the catch all route off on its own and ensuring it applies after everything, we restore the original functionality while still resolving the issue the original change was trying to achieve.
=> FIX Separating ModelAsController catch-all route

code/Controllers/ContentController.php
Hello @robbieaverill, please check my assumption first...it's been a long time since I have last used SS (v3.2 was my last, if i remember correctly)
in the following lines 438:
```php
if (isset($this->templates[$action]) && $this->templates[$action]
|| (isset($this->templates['index']) && $this->templates['index'])
|| $this->template
) {
return parent::getViewer($action);
}
```
It looks (I really mean it, "looks", i haven't checked the parent code) like the 1st two (same-line) conditions should be wrapped inside `()` while checking for a non-index action template like it's done in the following combined condition for the 'index' action .... if NOT just kill this PR at once. :-)
If the answer is YES then we could just use on function calls `!empty(...)` which has the same effect as …
=> simplify code using !empty

code/model/SiteTree.php
fixed for "PHP Deprecated:  Function create_function() is deprecated in \cms\code\model\SiteTree.php on line 2116" while using PHP 7.2
=> fixed deprecated create_function() in PHP 7.2

_config/config.yml
Copied directly from the class definition, but just to improve visibility of these settings which are highly impactful to CMS performance.
=> MINOR: Add CMS specific hierarchy config

code/Controllers/CMSMain.php
Only relevant if https://github.com/silverstripe/silverstripe-framework/pull/8380 is avialable,
however coded defensively so it can be merged before that PR if needs 
be.
See https://github.com/silverstripe/silverstripe-framework/issues/8379
* silverstripe/silverstripe-cms#2250
=> FIX: Use Hierarchy::prepopulate_numchildren_cache in tree-generation

code/Controllers/CMSMain.php, tests/behat/features/search-for-a-page.feature, tests/php/Controllers/CMSMainTest.php
Fixes the failing Behat tests in admin for when https://github.com/silverstripe/silverstripe-framework/pull/8414 and https://github.com/silverstripe/silverstripe-admin/pull/664 are merged.
The tests here won't pass until framework at least is merged
Issue: https://github.com/silverstripe/silverstripe-cms/issues/2251
=> FIX Update field names in Behat tests for new search form namespacing

code/model/SiteTree.php
When resolving a relative link it can be that no valid parent node is reached ... handle this condition gracefully.
=> do not die if there is no parent in RelativeLink

code/Controllers/CMSMain.php
Fixes https://github.com/silverstripe/silverstripe-cms/issues/2285
=> FIX CMSMain::duplicate() now checks canCreate() but not canEdit()

tests/php/Controllers/CMSPageHistoryControllerTest.php
Parent issues silverstripe/silverstripe-versioned-admin#67 and silverstripe/silverstripe-cms#2277
Once https://github.com/silverstripe/silverstripe-versioned-admin/pull/71 got merged in, the CMSPageHistoryController started failing because the new CMSPageHistoryViewerController was getting injected.
=> MINOR Update CMS test to explicitetly register the CMSPageHistoryController

code/Model/SiteTree.php
This PR updates `SiteTree::BackLinkTracking` to use some convoluted inner joins to avoid having to do individual query on each result to check for its existence.
It also alter queries to add the `DependentLinkType` alias field in the select statement which seems to give us a slight performance improvement over looping over all the results and adding it manually.
* https://github.com/silverstripe/silverstripe-versioned/issues/189
=> MINOR Speed up DependentPages by shifting existence check to table join

code/Search/ContentControllerSearchExtension.php
Resolves https://github.com/silverstripe/silverstripe-cms/issues/658
=> FIX 'Search' text in default search form should be a placeholder

tests/php/Controllers/CMSPageHistoryControllerTest.php, tests/php/Controllers/CMSPageHistoryControllerTest/HistoryController.php
Fixes the tests in the 4.3 branch. Ideally we could modify the injector config OR the url_priority config so that the CMS module's history controller would be loaded first, but this doesn't seem to work in functional tests. I've added a new stub controller with a different route to ensure it can be tested in isolation.
=> FIX CMSPageHistoryControllerTest now uses a stub controller to avoid URL conflicts with versioned-admin

tests/php/Model/SiteTreeTest.php
This PR updates the CMS unit test to work with the new configurable resource dir.
* https://github.com/silverstripe/silverstripe-framework/issues/7932
* https://github.com/silverstripe/silverstripe-framework/pull/8519
=> MINOR Update CMS test to work with configurable resource dir

code/Controllers/CMSMain.php, tests/php/Controllers/CMSMainTest.php
This is a follow up from this PR. https://github.com/silverstripe/silverstripe-cms/pull/2033
Basically `CMSMain::CanOrganiseSitetree` is kind of coded in a silly way right now.
This makes it unsilly.
=> MINOR Clean up CMSMain::CanOrganiseSitetree

code/Model/SiteTree.php, tests/php/Model/SiteTreeActionsTest.php
Add to Campaign button is now in an extension in the campaign-admin module.
Requires https://github.com/silverstripe/silverstripe-campaign-admin/pull/134
Issue: https://github.com/silverstripe/silverstripe-campaign-admin/issues/19
=> FIX Remove coupling from SiteTree to campaign admin module

code/Controllers/ContentController.php, code/Controllers/ModelAsController.php, code/Model/SiteTree.php, tests/php/Controllers/ModelAsControllerTest.php
Was double url encoding (once in database value, then again in request)
Fixes https://github.com/silverstripe/silverstripe-framework/issues/8723
=> FIX Multibyte URL routing

code/Controllers/ContentController.php, code/Controllers/ModelAsController.php, code/Model/SiteTree.php, tests/php/Controllers/ModelAsControllerTest.php
This backports #2365 so it will be applied to all SS 4.x releases.
See https://github.com/silverstripe/silverstripe-blog/issues/488#issuecomment-460637199 for justification
=> FIX Multibyte URL routing (backport)

tests/php/Model/SiteTreeTest.php
The test originally is testing that the date is included in an underlying SQL query as an argument. I've changed this in https://github.com/silverstripe/silverstripe-versioned/pull/213, so have updated this test to write an old page, set the reading archive date and assert that it can return the one page from it instead.
Issue: https://github.com/silverstripe/silverstripe-versioned/issues/194
=> SiteTreeTest::testReadArchiveDate() now tests ORM results rather than underlying sql arguments

code/Controllers/CMSMain.php
The current implementation doesn't scale,
and due to the proliferation of versioned objects
no longer fully works (e.g. doesn't publish all files).
Fixes https://github.com/silverstripe/silverstripe-cms/issues/2406
=> API Deprecated CMSMain->publishall()

code/Controllers/CMSPageAddController.php
Bootstrap 4 alerts are the default in SilverStripe 4.4, this one is custom so was missed during the update
=> FIX Use Bootstrap 4 alert for page type restriction message when adding a page

code/Model/SiteTree.php
This causes issues as content blocks can also be 'Dependent pages'. So it currently links to a page with the ID of the content block.
=> FIX Allow all types of content to be linked in dependent pages

code/Controllers/CMSMain.php, code/Controllers/CMSSiteTreeFilter_ChangedPages.php, code/Controllers/ModelAsController.php, code/Model/SiteTree.php, code/Reports/BrokenLinksReport.php, code/Reports/RecentlyEditedReport.php, code/Tasks/MigrateSiteTreeLinkingTask.php, code/Tasks/SiteTreeMaintenanceTask.php
We assume to assuming SiteTree's table name as a constant.
That precludes some mad scientist from renaming that table in their YML config which I think should be a supported use case. e.g.:
```yml
SilverStripe\CMS\Model\SiteTree:
table_name: SomethingOtherThanSiteTree
```
=> MINOR Do not assume SiteTree's table will always be call SiteTree.

tests/php/Tasks/MigrateSiteTreeLinkingTaskTest.php
Comparing every single field is unnecessary and brittle, only the IDs
need to be compared.
Notably this tripped over a potential bug fix in
https://github.com/silverstripe/silverstripe-framework/pull/8591
but the change should be incorporated regardless.
=> FIX: Make test comparison less brittle in MigrateSiteTreeLinkingTaskTest

code/Controllers/CMSMain.php
If a module augments the allowed pagetypes based on external conditions, the Hints Cache Key will not cover these conditions and may cause incorrect output. An example of this is Subsites, which allows each Subsite to have a different set of allowed pagetypes.
Since this is technically new API, it'd normally require a new minor release, however this extension point is being introduced purely in pursuit of fixing a bug, so I'd like to get it in as a patch update for the last few minor releases.
=> NEW Add updateHintsCacheKey extension point to fix invalid caching

code/Controllers/CMSPageAddController.php, code/Controllers/LeftAndMainPageIconsExtension.php
Fixes silverstripe/silverstripe-admin#872
=> FIX Only add page font icon classes if there's no icon image defined

code/Model/VirtualPage.php
4.4.x-dev uses Bootstrap 4 alerts, so this is a "bug fix" =)
Before:
After:
=> FIX Virtual page notice now uses Bootstrap 4 alerts

code/Model/SiteTree.php, tests/php/Model/SiteTreeBacklinksTest.php, tests/php/Model/SiteTreeBacklinksTest.yml, tests/php/Model/SiteTreeBacklinksTestContentObject.php
Content blocks and other DataObjects that contain HTMLText fields are
also used in the 'Dependent pages' report for each page in the CMS,
however these objects may have neither a Title field, nor a name to
describe them. Instead of showing an empty field in the Title column for
this table, we can instead show "Untitled " with the localised singular
name appended.
Resolves #2428
=> FIX display recognisable names for dependent content with no title

code/Model/RedirectorPage.php
The `onBeforeWrite` and `onAfterWrite` methods have been changed to `protected` in `DataObject` and `SiteTree` but have been missed out from `RedirectorPage` so it errors out.
=> Changing to protected to match the rest of the changes

code/Controllers/ContentController.php
A replacement PR for the [closed one on framework](https://github.com/silverstripe/silverstripe-framework/pull/8805), which explicitly disables caching through headers when a browser requests a page via the CMS Preview or in draft state.
Resolves [silverstripe/silverstripe-framework#8804](https://github.com/silverstripe/silverstripe-framework/issues/8804).
=> FIX Disable caching on page previews (CMSPreviews or stage=Stage)

_config/cache.yml, code/Controllers/LeftAndMainPageIconsExtension.php
We might be outliers but we've found that a good chunk of time (7ish%) on a request to the admin was being taken up by getting the page icons. These should only change when adding a new page which from my understanding would require a dev/build anyways so the cache wouldn't be any big issue
=> Cache page icons

code/Controllers/SilverStripeNavigatorItem_LiveLink.php, code/Controllers/SilverStripeNavigatorItem_StageLink.php, code/Model/RedirectorPage.php, code/Model/SiteTree.php
Existing functionality is limited to `RedirectorPage`
Another option would be to use the HiddenClass methodology
=> Negotiator amends: Make it possible to disable Preview links in the CMS

code/Model/SiteTree.php
Fixes issue - https://github.com/silverstripe/silverstripe-cms/issues/2502
=> FIX: If no parent in RelativeLink() return null

tests/php/Model/SiteTreeTest.php
This reverts a change from #2533 
The generic `expectException` could pass from an exception thrown in the first write() when we are only wanting an error from the second one.
=> Restore old exception assertion

code/Controllers/CMSMain.php
I'm trying to create a custom controller that extends CMSPageEditController for certain object types. I found that the class `CMSPageEditController` is explicitly used in several places and I wondered if it makes sense to refactor it to use `SiteTree->CMSEditLink()` as this would allow overriding the link directly from the object class.
Please see the commit log for details. Any feedback welcome.
=> Update docs and remove duplication

code/Controllers/CMSSiteTreeFilter_PublishedPages.php
* published pages filter was missing the default filtering functionality
Search by specific page type and for published pages
**Actual result**
Published pages of any page type
**Expected result**
Published pages of specific page type
https://github.com/silverstripe/silverstripe-cms/issues/2540
https://github.com/silverstripe/silverstripe-cms/issues/2415
=> BUG: Published pages filter correction (missing default filter)

code/Forms/SiteTreeURLSegmentField.php, code/Model/SiteTree.php, tests/php/Forms/SiteTreeURLSegmentFieldTest.php
`SiteTreeURLSegmentField` accepts a URL Prefix property, but just ignores the value given to it.
* #1364
=> BUG Honour URL suffix on URL Segment field

_config/version.yml
Issue https://github.com/silverstripe/silverstripe-installer/issues/276
Related PR (merged) to add functionality https://github.com/silverstripe/silverstripe-framework/pull/9628
Reason that recipes are added here rather than within silverstripe/recipe-core/cms is because recipes are included in the projects vendor folder like normal modules
If we were to add the config in the recipes, then we would need to have a pair of seperate yml files copied into the project app/_config folder which would be pretty annoying for a relatively minor feature
=> NEW Set VersionedProvider labels for recipe-core and recipe-cms

code/Model/SiteTree.php
* unpublish action no longer requires explicit publish permission
* projects with out of the box setup will not be impacted as unpublish permission falls back to publish permission
* the change only impacts projects which use explicit and separate permissions for publish / unpublish actions
* note that separating these permissions makes sense in cases where publishing requires an audit and is considered risky action while unpublishing not so much
https://github.com/silverstripe/silverstripe-cms/issues/2579
=> BUG: Unpublish permission decoupled from publish permission.

code/Controllers/CMSSiteTreeFilter.php, tests/php/Controllers/CMSSiteTreeFilterTest.php, tests/php/Controllers/CMSSiteTreeFilterTest.yml
Affected version:
`4.5.1`
URL segment search lacks encoding which causes the search results to omit some pages.
Consider a page with the following URL segment:
`lake-wanaka+adventure`
Searching for this page will yield no results because the search matches raw value which doesn't work as the DB value is stored in encoded format which looks like this:
`lake-wanaka%2Badventure`
Apply encoding to all places where URL segment value is passed to DB lookup.
* we can't rely on `URLSegmentFilter` to sanitise the values in general because the sanitisation rules are configurable via the `default_replacements` configuration API
* we need to make sure any encoded values can be used for search
https://github.com/silverstripe/silverstripe-cms/issues/2359
=> BUG: URL segment filter correction for CMS page search.

tests/php/Model/SiteTreeTest.php
That test is no longer needed because we won't allow you to save a page with an underscore in its URLSegment.
This should fix the broken recipe-cms build and some of the sink build.
=> BUG Remove broken RESOURCES_DIR test

.travis.yml, tests/php/Search/SearchFormTest.php
This matrix entry was missing `PHPUNIT_TEST=1`, and therefore wasn't running any tests. This was masking a test failure with PostgreSQL, and this test suite is [currently failing in silverstripe/installer](https://travis-ci.org/github/silverstripe/silverstripe-installer/jobs/737110775).
=> MNT Fix unit tests not running on PGSQL build

code/Controllers/CMSPageAddController.php, tests/behat/features/create-a-page.feature, tests/behat/src/FixtureContext.php
Issue https://github.com/silverstripe/silverstripe-cms/issues/2396
Blocked by https://github.com/silverstripe/silverstripe-framework/pull/9741
Failed behat test requires the above PR to be merged so that the radio button can be disabled
When a user lacks the permission to create top-level pages, the following will now happen:
a) Disables the "Top-level" radio input
b) Auto-selects the "Under another page" radio input
=> ENH Disable option to create top-level pages based on permissions

_config/graphql.yml, code/GraphQL/LinkablePlugin.php
It had been accidentally removed from the registry.
Refactored so that it's always its own argument to the query, and should not apply to list queries, only single record queries.
=> BUGFIX: Restore, refactor getByLink plugin

lang/sl.yml
Translations for later versions is corrected via transifex. Can you please use the latest corrections also for the 4.6 version. 
cc @dnsl48
=> UX updates of translation to Slovenian (for 4.6)

tests/behat/features/create-a-page.feature, tests/behat/features/publish-a-page.feature, tests/behat/src/FixtureContext.php
Issue https://github.com/silverstripe/silverstripe-behat-extension/issues/200
Will need behat-extension 4.3.1 tagged before the 'confirm the dialog' test passes
=> MNT Use behat-extension function for clicking elements

_config/graphql-legacy.yml
Resolves https://github.com/silverstripe/silverstripe-graphql/issues/376
=> BUGFIX: Ensure SiteTree and ancestors always available in the CMS

code/Model/VirtualPage.php
This replaces using the `MetaTags` method as replacing or removing a canonical requires string manipulation vs unsetting an array key, and is preferred.
Additionally, the virtual page can disable generating a canonical for the proxied page.
resolves #2637
=> UPDATE generate canonical via MetaComponents

composer.json, lang/en.yml, templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PreviewPanel.ss
Issue https://github.com/silverstripe/silverstripe-cms/issues/1945#issuecomment-869322412
This accompanies a [logic patch in the admin module](https://github.com/silverstripe/silverstripe-admin/pull/1086) to ensure that when no preview state is available for a pagetype, it renders a message stating this. Previously a broken layout would appear instead.
=> FIX Show 'No preview available' message for pages with no state

tests/php/Controllers/CMSMainTest.php, tests/php/Model/SiteTreePermissionsTest.php
Issue https://github.com/silverstripe/recipe-cms/issues/47
=> MNT Use logInAs() for unit tests

code/Model/SiteTree.php
Currently, if there are no anchors found in the page content, the updateAnchorsOnPage extension is not called.
This proposed change will call the updateAnchorsOnPage extension regardless of the page content.
=> FIX updateAnchorsOnPage extension not always called

code/Model/SiteTreeLinkTracking_Parser.php, tests/php/Model/SiteTreeLinkTrackingTest.php, tests/php/Model/SiteTreeLinkTracking_Extension.php
Currently, the SiteTreeLinkTracking_Parser only checks the page's content for anchors.
As a result any anchors that have been added or modified by the updateAnchorsOnPage extension in the getAnchorsOnPage method are marked ss-broken.
This change updates SiteTreeLinkTracking_Parser to get the anchors from the getAnchorsOnPage function on SiteTree.
This will allow for more consistent RegEx matching and allow the updateAnchorsOnPage extension to be used when checking for broken links.
=> FIX SiteTreeLinkTracking_Parser should use the getAnchorsOnPage

code/Model/VirtualPage.php, tests/php/Model/VirtualPageTest.php
The canonical tag should be a `link` tag not `meta`, see https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#rel-canonical-link-method
=> FIX canonical tag on VirtualPage

code/Model/SiteTree.php, tests/php/Model/SiteTreeTest.php
Fixes #2580 
The call to `Director::makeRelative` transforms absolute links into relative links, but is done separately to checking for a possible homepage URL. Previously, this meant that you could pass in "https://example.co.nz/about-us" or "about-us" and get the same result, but passing in "https://example.co.nz/" and "/"  would give _different_ results.
This commit performs the transformation to a relative link _before_ checking if the path should be for the home page, which leads to more consistent results.
=> FIX: Treat absolute links in a consistent manner in get_by_link.

code/Model/SiteTree.php
If not set explicitly, the field name is taken from the title and changes if the site uses a different locale.
=> FIX SiteTree visibility field name

code/Controllers/SilverStripeNavigatorItem_Unversioned.php, lang/en.yml
Currently only Versioned DataObjects are enabled for the CMS preview. Without a navigator item, non-versioned DataObjects aren't allowed to display in the preview panel even if they implement CMSPreviewable.
Note that this state will still need to be added to the list of allowed states in the .cms-preview entwine logic which can be done like so:
```js
$('.cms-preview').entwine('ss.preview').AllowedStates().push('Unversioned');
```
Allowing the state mannualy as above is unnecessary if silverstripe/silverstripe-admin#1258 gets merged in.
This isn't particularly useful without silverstripe/silverstripe-admin#1250 but I guess it would allow someone to preview non-versioned `SiteTree` objects (assuming it's even possible to remove the `Versioned` extension from `SiteTree` without causing …
=> NEW Add preview state for non-versioned DataObjects.

code/Controllers/CMSMain.php, code/Model/SiteTree.php
GridFieldComponents packaged with silverstripe/framework are injectable as of 4.11.0 (see silverstripe/silverstripe-framework#10204)
Explicitly invoking the injector here instead of using `create()` allows backwards compatability with framework < 4.11.0 while ensuring dependency injection is still used from 4.11.0 onwards.
See silverstripe/silverstripe-admin#1286 for (brief) discussion of this approach vs using `::create()`.
=> ENH Prefer dependency injection for GridFieldComponents

code/Model/SiteTree.php, composer.json, tests/php/Model/SiteTreeTest.php
Issue https://github.com/silverstripe/silverstripe-cms/issues/2708
Will require [this PR](https://github.com/silverstripe/silverstripe-framework/pull/10235) to be merged first
=> NEW Include version number in meta generator tag

code/Search/SearchForm.php
If a user changes the search form URL start parameter to a negative number (`&start=-10`), this will cause a server error.
This change fixes this problem by making sure start is always an int and is never less than zero.
=> FIX Ensure search form start var is not a negative number

code/Model/SiteTree.php, tests/php/Controllers/SiteTreeTest_NamespaceMapTestController.php, tests/php/Model/SiteTreeTest.php, tests/php/Page/SiteTreeTest_NamespaceMapTest.php
Creates a config variable where you can define a mapping between your Pages namespace and your Controllers namespace.
A common desired pattern is to keep things properly organised by having `App\Pages\MyPageType` and `App\Control\MyPageTypeController` - but this isn't currently caught by the ✨ "magic" ✨ . This allows for a global setting, rather than the one-off afforded by `$controller_name`.
Opens the door for adding a default map in 5 - maybe auto-substituting Page => Control, but that's another debate to have.
=> FEATURE add config var for namespace mapping page->control

code/Controllers/CMSMain.php
Currently the "Page Type" values in the sitetree list view aren't translated. e.g. in the below screenshot, the translation for "Virtual Page" isn't being pulled through.
=> FIX Translate pagetype names in list view
